{{- range $profile, $values := .Values.kcm.kof.clusterProfiles }}
{{- if $values.create_secrets }}
{{- range $values.secrets }}
{{- /* Checking that the secret isn't created yet to avoid credentials regeneration */}}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace . ) }}
{{- $username := randAlpha ($.Values.global.random_username_length | int) }}
{{- $password := randAlpha ($.Values.global.random_password_length | int) }}
{{- if $secret }}
{{- $username = index $secret.data "username" | b64dec }}
{{- $password = index $secret.data "password" | b64dec }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ . }}
  namespace: {{ $.Release.Namespace }}
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
type: Opaque
{{- end }}
{{- end }}
{{- end }}
