# This job is required for now to avoid the error
# `admission webhook "validation.multiclusterservice.k0rdent.mirantis.com"
# denied the request: the MultiClusterService is invalid:
# the template is not valid:`
# because `helm.sh/hook: pre-install` in `ServiceTemplate`-s installs them first,
# but they still need some time to get `VALID` status.
apiVersion: batch/v1
kind: Job
metadata:
  name: kof-wait-valid-svctmpl
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: busybox
          command: ["/bin/sleep", "10"]
