{{- if .Values.promxy.enabled }}
  {{- $secret_name := include "promxy.secretname" . }}
  {{- $secret := lookup "v1" "Secret" $.Release.Namespace $secret_name }}
  {{- $secret_key := "config.yaml" }}
  {{- $secret_value := "" }}
  {{- if $secret }}
    {{- $secret_value = index $secret.data $secret_key | b64dec }}
  {{- end }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secret_name }}
  namespace: {{ $.Release.Namespace }}
stringData:
  {{ $secret_key }}: {{ $secret_value | quote }}
type: Opaque
{{- end }}
