{{- if .Values.promxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "promxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promxy.labels" . | nindent 4 }}
    {{- if .Values.promxy.extraLabels}}
    {{ toYaml .Values.promxy.extraLabels | nindent 4 }}
    {{- end}}
  {{- with .Values.promxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
