{{- if and .Values.promxy.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- with .Values.promxy.service.annotations }}
  annotations:
{{ toYaml . | indent 4}}
{{- end }}
  labels:
    {{- include "promxy.labels" . | nindent 4 }}
    {{- if .Values.promxy.extraLabels}}
    {{ toYaml .Values.promxy.extraLabels | nindent 4 }}
    {{- end}}
  name: {{ .Release.Name }}-promxy
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.promxy.service.clusterIP }}
  clusterIP: {{ .Values.promxy.service.clusterIP }}
{{- end }}
{{- if .Values.promxy.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.promxy.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.promxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.promxy.service.loadBalancerIP }}
{{- end }}
{{- if .Values.promxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.promxy.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.promxy.service.servicePort }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "promxy.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.promxy.service.type }}"
{{- end }}
