{{- if and (not .Values.s3.existingSecret) .Values.s3.credentials.accessKey .Values.s3.credentials.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-logs-exporter.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audit-logs-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.s3.credentials.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.s3.credentials.secretKey | quote }}
{{- end }}
