{
 "title": "Cluster API",
 "description": "Built from https://github.com/kubernetes-monitoring/kubernetes-mixin",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "kof/control-plane-metrics-monitor"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"$job\"}, cluster)"
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(workqueue_adds_total{job=\"$job\", pod=~\"capi.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Capi Controller",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", job=\"$job\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Capi Infrastructure Providers",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", job=\"$job\",pod!~\"kcm.*\"}"
    }
   ]
  },
  {
   "title": "Cluster API",
   "type": "text",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "\nThis dashboard aims to present state of the service following \n[The Four Golden Signals](https://sre.google/sre-book/monitoring-distributed-systems/) principle"
   }
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{cluster=\"$cluster\", job=\"$job\", pod=\"$pod\"}[$__rate_interval])) by (cluster, name, le))",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}name}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"2..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"3..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"4..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"5..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster=\"$cluster\", job=\"$job\", pod=\"$pod\"}[$__rate_interval])) by (cluster, name)",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}name}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Work Queue Retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{cluster=\"$cluster\", job=\"$job\",pod=\"$pod\"}[$__rate_interval])) by (cluster, name)",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}name}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"2..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"3..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"4..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"5..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{cluster=\"$cluster\", job=\"$job\",pod=\"$pod\"}[$__rate_interval])) by (cluster, name)",
     "legendFormat": "{{\"{{\"}}cluster}} {{\"{{\"}}name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\", job=\"$job\"}",
     "legendFormat": "{{\"{{\"}}pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{\"{{\"}}pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", job=\"$job\"}",
     "legendFormat": "{{\"{{\"}}pod}}"
    }
   ]
  }
 ]
}