{{- if (index .Values "cluster-api-visualizer").ingress.enabled }}
{{- $path := (index .Values "cluster-api-visualizer").ingress.path -}}
{{- $pathType := (index .Values "cluster-api-visualizer").ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if (index .Values "cluster-api-visualizer").ingress.annotations }}
  annotations:
{{ toYaml (index .Values "cluster-api-visualizer").ingress.annotations | indent 4 }}
{{- end }}
  labels:
  {{- include "cluster-api-visualizer.labels" . | nindent 4 }}
  {{ with (index .Values "cluster-api-visualizer").ingress.extraLabels }}
{{ toYaml . | indent 4 }}
  {{ end }}
  name: {{ template "cluster-api-visualizer.fullname" . }}-cluster-api-visualizer
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ (index .Values "cluster-api-visualizer").ingress.ingressClassName }}
  rules:
  {{- range (index .Values "cluster-api-visualizer").ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        - path: {{ $path }}
          pathType: {{ $pathType }}
          backend:
            service:
              name: capi-visualizer
              port:
                number: 8081
  {{- end -}}
{{- if (index .Values "cluster-api-visualizer").ingress.tls }}
  tls:
{{ toYaml (index .Values "cluster-api-visualizer").ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
