{
 "title": "VictoriaMetrics - operator",
 "description": "Overview for operator VictoriaMetrics v0.25.0 or higher",
 "tags": [
  "operator",
  "VictoriaMetrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(operator_log_messages_total,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(operator_log_messages_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(vm_app_version{job=\"$job\", instance=\"$instance\"},  version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">$version</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CRD Objects count by controller",
   "type": "stat",
   "description": "Number of objects at kubernetes cluster per each controller",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(operator_controller_objects_count{job=~\"$job\",instance=~\"$instance\"}) by (controller)",
     "legendFormat": "{{`{{controller}}`}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Prometheus Objects watchers",
   "type": "stat",
   "description": " Shows per namespace watchers for Prometheus Operator objects (ServiceMonitors, PodMonitors, etc) ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(operator_prometheus_converter_active_watchers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Electer Leaders",
   "type": "stat",
   "description": " Number of operator instances with obtained leader status. \n Value above 1 indicates that instances with the same job may behave incorrectly.\n It's recommend to check Operator logs. ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(leader_election_master_status{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active workers",
   "type": "stat",
   "description": " Shows number of active reconcile workers",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Converter Watch events",
   "type": "timeseries",
   "description": " Shows amount of Prometheus Operator objects processed by Operator.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(operator_prometheus_converter_watch_events_total{job=~\"$job\"}[$__interval])) by (event_type,object_type_name)",
     "legendFormat": "{{`{{object_type_name}}`}} {{`{{event_type}}`}}"
    }
   ]
  },
  {
   "title": "Reconciliation rate by controller",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=~\"$job\",instance=~\"$instance\",result=~\"requeue_after|requeue|success\"}[$__rate_interval])) by(controller)",
     "legendFormat": "{{`{{controller}}`}}"
    }
   ]
  },
  {
   "title": "Log message rate",
   "type": "timeseries",
   "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(operator_log_messages_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{`{{label_name}}`}}"
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "reconcile errors by controller",
   "type": "timeseries",
   "description": "Non zero metrics indicates about error with CR object definition (typos or incorrect values) or errors with kubernetes API connection.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by(controller) > 0 ",
     "legendFormat": "{{`{{controller}}`}}"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=~\"$job\",instance=~\"$instance\",result=\"error\"}[$__rate_interval])) by(controller) > 0",
     "legendFormat": "result errors: {{`{{controller}}`}}"
    }
   ]
  },
  {
   "title": "throttled reconcilation config events",
   "type": "timeseries",
   "description": "Operator limits number of reconcile configuration events to 5 events per 2 seconds by default.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(operator_reconcile_throttled_events_total[$__rate_interval])) by(controller)",
     "legendFormat": "{{`{{controller}}`}}"
    }
   ]
  },
  {
   "title": "Wokring queue depth",
   "type": "timeseries",
   "description": "Number of objects waiting in the queue for reconciliation. Non-zero values indicate that operator cannot process CR objects changes with the given resources.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(workqueue_depth{job=~\"$job\",instance=~\"$instance\"}) by (name)",
     "legendFormat": "{{`{{label_name}}`}}"
    }
   ]
  },
  {
   "title": "Reconcilation latency by controller",
   "type": "timeseries",
   "description": " For controllers with StatefulSet it's ok to see latency greater then 3 seconds. It could be vmalertmanager,vmcluster or vmagent in statefulMode.\n\n For other controllers, latency greater then 2 second may indicate issues with kubernetes cluster or operator's performance.\n ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by(le,controller) )",
     "legendFormat": "q.99 {{`{{controller}}`}}"
    }
   ]
  },
  {
   "title": "Rest client requests",
   "type": "timeseries",
   "description": "Number of HTTP requests to the Kubernetes API server break down by code and method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"$job\"}[$__interval])) by (method,code)",
     "legendFormat": "{{`{{method}}`}} {{`{{code}}`}}"
    }
   ]
  },
  {
   "title": "Concurrent reconcile ($instance)",
   "type": "timeseries",
   "description": "Shows how many ongoing reconcile events are taking place, where:\n* `max` - equal to the value of flag`-controller.maxConcurrentReconciles`;\n* `current` - current number of reconcile workers processing CRD objects.\n\nWhen `current` hits `max` constantly, it means operator cannot process events in time. It should be either increased value for flag `-controller.maxConcurrentReconciles` or allocated  additional CPU resources to the operator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "max(max_over_time(controller_runtime_active_workers{job=~\"$job\"}[$__interval]))",
     "legendFormat": "Current"
    },
    {
     "expr": "min(controller_runtime_max_concurrent_reconciles{job=~\"$job\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Go scheduling latency",
   "type": "timeseries",
   "description": "Shows the time goroutines have spent in runnable state before actually running. The lower is better.\n\nHigh values or values exceeding the threshold is usually a sign of insufficient CPU resources or CPU throttling. \n\nVerify that service has enough CPU resources. Otherwise, the service could work unreliably with delays in processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (job, instance, le))) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"}) ",
     "legendFormat": "requested from system"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}) ",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "CPU ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) ",
     "legendFormat": "CPU cores used"
    }
   ]
  },
  {
   "title": "Goroutines ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC duration ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n/\nsum(rate(go_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg gc duration"
    }
   ]
  }
 ]
}