# GitHub Dependabot configuration for k0rdent/kof
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor npm dependencies in the React web application
  - package-ecosystem: "npm"
    directory: "/kof-operator/webapp/collector"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Etc/UTC"
    # Only create PRs for security vulnerabilities
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
    versioning-strategy: "lockfile-only"

  # Monitor Go module dependencies in the operator
  - package-ecosystem: "gomod"
    directory: "/kof-operator"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "github.com/prometheus/prometheus" # incompatibility with istio package
      - dependency-name: "k8s.io/*" # should be aligned with KCM and VictoriaMetrics

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"

  - package-ecosystem: helm
    directories:
      - "/charts/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
