{{- range $name, $value := .Values.kcm.kof.mcs }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ $name }}-remote
spec:
  clusterSelector:
    matchLabels: {{ $value.matchLabels | toYaml | nindent 6 }}
  serviceSpec:
    services:
    {{- range $value.secrets }}
    - name: secret-{{ . }}
      template: kof-propagation-{{ $.Chart.Version | replace "." "-" }}
      namespace: {{ $.Values.kcm.namespace }}
      values: |
        propagation:
          enabled: true
          data: |
            {{`{{ setField "secret-`}}{{ . }}{{`" "metadata.namespace" "`}}{{ $.Release.Namespace }}{{`" | nindent 14 }}`}}
    {{- end }}
    templateResourceRefs:
    {{- range $value.secrets }}
    - identifier: secret-{{ . }}
      resource:
        apiVersion: v1
        kind: Secret
        name: {{ . }}
        namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- end }}
