{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmcluster.enabled }}
{{- if .Values.istio_endpoints }}
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.global.clusterName }}-logs.{{ .Release.Namespace }}.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 9428
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: {{ .Release.Name }}-victoria-logs-single-server.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-vminsert
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.global.clusterName }}-vminsert.{{ .Release.Namespace }}.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 8480
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: vminsert-cluster.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-vmselect
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.global.clusterName }}-vmselect.{{ .Release.Namespace }}.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 8481
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: vmselect-cluster.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
{{- end }}
{{- end }}
