{{- if index .Values "victoria-logs-multilevel-select" "enabled" }}
apiVersion: kof.k0rdent.mirantis.com/v1beta1
kind: VMStorageConnection
metadata:
  name: {{ .Release.Name }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  cluster_ref:
    kind: VLCluster
    name: kof-mothership-logs-multilevel-select
    namespace: {{ .Release.Namespace }}
  target_storage_node:
    address: {{ .Release.Name }}-victoria-logs-cluster-vlselect.{{ .Release.Namespace }}.svc:9471
{{- end }}
    