{{- if index .Values "victoria-metrics-multilevel-select" "enabled" }}
apiVersion: kof.k0rdent.mirantis.com/v1beta1
kind: VMStorageConnection
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  cluster_ref:
    kind: VMCluster
    name: kof-mothership-metrics-multilevel-select
    namespace: {{ .Release.Namespace }}
  target_storage_node:
    address: {{ include "kof-storage.vmSelectAddress" . }}/select/0/prometheus
{{- end }}
