{{- if and .Values.victoriametrics.vlcluster_audit.enabled .Values.victoriametrics.vlcluster_audit.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-vlinsert-audit-logs
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: audit-logs
      app.kubernetes.io/name: vlinsert
      managed-by: vm-operator

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-vlselect-audit-logs
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: audit-logs
      app.kubernetes.io/name: vlselect
      managed-by: vm-operator

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-vlstorage-audit-logs
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: audit-logs
      app.kubernetes.io/name: vlstorage
      managed-by: vm-operator
{{- end }}
