{{- $global := .Values.global | default (dict "image" dict) }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- $spec := deepCopy .Values.victoriametrics.vmalert.spec }}
  {{- if not $spec.remoteRead.url }}
  {{- $_ := set $spec.remoteRead "url" (printf "%s/select/0/prometheus" (include "kof-storage.vmSelectLocalUrl" .)) }}
  {{- end }}
  {{- if not $spec.remoteWrite.url }}
  {{- $_ := set $spec.remoteWrite "url" (printf "%s/insert/0/prometheus/api/v1/write" (include "kof-storage.vmInsertLocalUrl" .)) }}
  {{- end }}
  {{- if not $spec.datasource.url }}
  {{- $_ := set $spec.datasource "url" (printf "%s/select/0/prometheus" (include "kof-storage.vmSelectLocalUrl" .)) }}
  {{- end }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
