apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: regional-adopted
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-cluster-role: regional
  annotations:
    k0rdent.mirantis.com/kof-http-config: '{"dial_timeout": "1s", "tls_config": {"insecure_skip_verify": true}}'
spec:
  template: adopted-cluster-1-0-1
  credential: regional-adopted-cred
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-regional-domain: regional-adopted
      k0rdent.mirantis.com/kof-storage-values: |
        cert-manager:
          cluster-issuer:
            provider: self-signed
        grafana:
          ingress:
            enabled: false
      k0rdent.mirantis.com/kof-collectors-values: |
        metrics-server:
          enabled: true
          args:
            - --kubelet-insecure-tls
