apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: child-adopted
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/istio-role: member
    k0rdent.mirantis.com/kof-cluster-role: child
    k0rdent.mirantis.com/kof-regional-cluster-name: regional-adopted
spec:
  template: adopted-cluster-1-0-1
  credential: child-adopted-cred
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-collectors-values: |
        metrics-server:
          enabled: true
          args:
            - --kubelet-insecure-tls
