apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: regional-adopted
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/istio-role: member
    k0rdent.mirantis.com/istio-gateway: "true"
    k0rdent.mirantis.com/istio-mesh: "regional-adopted"
    k0rdent.mirantis.com/kcm-region-cluster: "true"
    k0rdent.mirantis.com/kof-cluster-role: regional
    k0rdent.mirantis.com/kof-cluster-name: regional-adopted
  annotations:
    k0rdent.mirantis.com/kof-http-config: '{"dial_timeout": "1s", "tls_config": {"insecure_skip_verify": true}}'
spec:
  template: adopted-cluster-1-0-1
  credential: regional-adopted-cred
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-collectors-values: |
        metrics-server:
          enabled: true
          args:
            - --kubelet-insecure-tls