apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: aws-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-storage-secrets: "true"
    k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
    k0rdent.mirantis.com/kof-cluster-role: regional
  annotations: {}
    # Custom promxy and grafana datasource http client config
    # k0rdent.mirantis.com/kof-http-config: '{"dial_timeout": "10s", "tls_config": {"insecure_skip_verify": true}}'
spec:
  template: aws-standalone-cp-1-0-16
  credential: aws-cluster-identity-cred
  cleanupOnDeletion: true
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    clusterAnnotations:
      k0rdent.mirantis.com/kof-regional-domain: aws-ue2.kof.example.com
      k0rdent.mirantis.com/kof-cert-email: mail@example.com
      k0rdent.mirantis.com/kof-storage-values: |
        victoriametrics:
          vmcluster:
            spec:
              vmstorage:
                storage:
                  volumeClaimTemplate:
                    spec:
                      resources:
                        requests:
                          storage: "10Gi"
        victoria-logs-cluster:
          vlstorage:
            persistentVolume:
              size: "10Gi"
        victoria-traces-cluster:
            persistentVolume:
              size: "10Gi"
      # Any custom values, e.g. https://docs.victoriametrics.com/helm/victorialogs-cluster/#parameters
      # k0rdent.mirantis.com/kof-storage-values: |
      #   victoria-logs-cluster:
      #     vlinsert:
      #       replicaCount: 2

      # `template: aws-standalone-cp` provides a default storage class:
      # k0rdent.mirantis.com/kof-storage-class: ebs-csi-default-sc

      # Default endpoints for `kof-regional-domain: aws-ue2.kof.example.com`:
      # k0rdent.mirantis.com/kof-write-metrics-endpoint: https://vmauth.aws-ue2.kof.example.com/vm/insert/0/prometheus/api/v1/write
      # k0rdent.mirantis.com/kof-read-metrics-endpoint: https://vmauth.aws-ue2.kof.example.com/vm/select/0/prometheus
      # k0rdent.mirantis.com/kof-write-logs-endpoint: https://vmauth.aws-ue2.kof.example.com/vli/insert/opentelemetry/v1/logs
      # k0rdent.mirantis.com/kof-read-logs-endpoint: https://vmauth.aws-ue2.kof.example.com/vls
      # k0rdent.mirantis.com/kof-write-traces-endpoint: https://vmauth.aws-ue2.kof.example.com/vti/insert/opentelemetry/v1/traces
      # k0rdent.mirantis.com/kof-read-traces-endpoint: https://vmauth.aws-ue2.kof.example.com/vts/select/jaeger

    region: us-east-2

    controlPlaneNumber: 1
    controlPlane:
      instanceType: t3.large

    workersNumber: 3
    worker:
      instanceType: t3.medium
