apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: region-aws-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-cluster-role: regional
    k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
    k0rdent.mirantis.com/kcm-region-cluster: "true"
spec:
  template: aws-standalone-cp-1-0-16
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    clusterAnnotations:
      k0rdent.mirantis.com/kof-storage-values: |
        victoriametrics:
          vmcluster:
            spec:
              vmstorage:
                storage:
                  volumeClaimTemplate:
                    spec:
                      resources:
                        requests:
                          storage: "10Gi"
        victoria-logs-cluster:
          vlstorage:
            persistentVolume:
              size: "10Gi"
        victoria-traces-cluster:
            persistentVolume:
              size: "10Gi"

    region: us-east-2

    controlPlaneNumber: 1
    controlPlane:
      instanceType: t3.large

    workersNumber: 3
    worker:
      instanceType: t3.large
