apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-eks-ue2
  namespace: kcm-system
spec:
  template: aws-eks-0-1-0
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
    clusterLabels:
      k0rdent.mirantis.com/kof-storage-secrets: "true"
      k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
  serviceSpec:
    priority: 100
    services:
      - name: ingress-nginx
        namespace: ingress-nginx
        template: ingress-nginx-4-11-3
      - name: cert-manager
        namespace: cert-manager
        template: cert-manager-1-16-2
        values: |
          cert-manager:
            crds:
              enabled: true
      - name: kof-storage
        namespace: kof
        template: kof-storage-0-1-1
        values: |
          global:
            storageClass: gp2
          victoriametrics:
            vmauth:
              ingress:
                host: vmauth.storage0.example.net
            security:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
          victoria-logs-single:
            server:
              storage:
                storageClassName: gp2
          grafana:
            ingress:
              host: vmauth.storage0.example.net
            security:
              credentials_secret_name: grafana-admin-credentials
          cert-manager:
            email: mail@example.net
          jaeger:
            ingress:
              enabled: false
              host: jaeger.example.com
---
apiVersion: kof.k0rdent.mirantis.com/v1alpha1
kind: PromxyServerGroup
metadata:
  labels:
    app.kubernetes.io/name: promxy-operator
    k0rdent.mirantis.com/promxy-secret-name: kof-mothership-promxy-config
  name: promxyservergroup-sample
  namespace: kof
spec:
  cluster_name: storage0
  targets:
    - "vmauth.storage0.example.net:443"
  path_prefix: "/vm/select/0/prometheus/"
  scheme: https
  http_client:
    dial_timeout: "5s"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      credentials_secret_name: "storage-vmuser-credentials"
      username_key: "username"
      password_key: "password"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: victoria-logs-storage0
  namespace: kof
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          key: username
          name: storage-vmuser-credentials
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          key: password
          name: storage-vmuser-credentials
  datasource:
    access: proxy
    isDefault: false
    name: storage0-logs
    type: "victoriametrics-logs-datasource"
    url: https://vmauth.storage0.example.net/vls
    basicAuth: true
    basicAuthUser: ${username}
    secureJsonData:
      basicAuthPassword: ${password}
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
