{{- range $component := append .Values.global.components "victoria-metrics-operator" }}
{{- if index $.Values $component "enabled" }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $component }}
  namespace: {{ include "kof.namespace" $ }}
  annotations:
    reconcile.fluxcd.io/requestedAt: "{{ now | unixEpoch }}"
    reconcile.fluxcd.io/forceAt: "{{ now | unixEpoch }}"
    helm.sh/resource-policy: keep # FluxCD is unable to delete all releases in the correct order
  labels:
    {{- include "kof.labels" $ | nindent 4 }}
    k0rdent.mirantis.com/component: {{ $component }}
spec:
  interval: {{ $.Values.flux.timeout }}
  timeout: {{ $.Values.flux.timeout }}
  {{- with index $.Values $component "dependsOn" }}
  dependsOn:
    {{- range $dep := . }}
    {{- if index $.Values $dep "enabled" }}
    - name: {{ $dep }}
      namespace: {{ include "kof.namespace" $ }}
    {{- end }}
    {{- end }}
  {{- end }}
  chartRef:
    kind: HelmChart
    name: {{ $component }}
    namespace: {{ $.Values.global.helmRepo.namespace }}
  install:
    createNamespace: {{ $.Values.flux.install.createNamespace  }}
    remediation:
      retries: {{ $.Values.flux.install.remediation.retries }}
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: {{ $.Values.flux.upgrade.retryInterval }}
  values:
    {{- $values := mergeOverwrite (dict) (index $.Values $component "values") }}

    {{- if eq $component "kof-mothership" }}
      {{- $values = mergeOverwrite $values (print `
      kcm:
        kof:
          repo:
            name: ` $.Values.global.helmRepo.name `
          operator:
            autoUpgrade: ` $.Values.autoUpgrade | fromYaml) }}

      {{- if $.Values.regionless.enabled }}
        {{- $values = mergeOverwrite $values (print `
        # Passing values to kof-operator.
        regionless:
          enabled: true
          domain: ` (quote $.Values.regionless.domain) `

        # Management cluster name.
        global:
          clusterName: ` (quote $.Values.regionless.clusterName) `
        kof-dashboards:
          grafana:
            dashboard:
              datasource:
                filters:
                  cluster: ` (quote $.Values.regionless.clusterName) `

        # Using VMCluster from kof-storage, but VMAlertManager - from kof-mothership.
        victoriametrics:
          vmcluster:
            enabled: false
        ` | fromYaml) }}
      {{- end }}

      {{- if $.Values.tls.selfSigned }}
        {{- $values = mergeOverwrite $values (`
        cert-manager:
          cluster-issuer:
            provider: self-signed
            name: selfsigned
        gateway:
          annotations:
            cert-manager.io/cluster-issuer: selfsigned
        ` | fromYaml) }}
      {{- end }}
    {{- end }}

    {{- if eq $component "victoria-metrics-operator" }}
      {{- if $.Values.regionless.enabled }}
        {{- $values = mergeOverwrite $values (`
        # Using VM-operator from kof umbrella as required for kof-mothership,
        # just enabling Gateway API for regionless.
        env:
          - name: VM_GATEWAY_API_ENABLED
            value: "true"
        ` | fromYaml) }}
      {{- end }}
    {{- end }}

    {{- if eq $component "kof-regional" }}
      {{- $values = mergeOverwrite $values (dict "autoUpgrade" $.Values.autoUpgrade) }}

      {{- if $.Values.regionless.enabled }}
        {{- $values = mergeOverwrite $values (print `
        # Using VM-operator and kof-operators from kof umbrella, not from kof-regional MCS.
        victoria-metrics-operator:
          enabled: false
        kof-operators:
          enabled: false

        # Using cert-manager installed to mgmt cluster by KCM, it has enableGatewayAPI.
        cert-manager:
          enabled: false

        # Switch MCS to the regionless setup.
        regionless:
          enabled: true
          clusterName: ` (quote $.Values.regionless.clusterName) `
          domain: ` (quote $.Values.regionless.domain) `
          certEmail: ` (quote $.Values.regionless.certEmail) `
        ` | fromYaml) }}
      {{- end }}

      {{- if $.Values.tls.selfSigned }}
        {{- $values = mergeOverwrite $values (`
        cert-manager:
          cluster-issuer:
            provider: self-signed
        storage:
          cert-manager:
            cluster-issuer:
              provider: self-signed
              name: selfsigned
          gateway:
            annotations:
              cert-manager.io/cluster-issuer: selfsigned
        ` | fromYaml) }}

        {{- if and $.Values.regionless.enabled ($.Values | merge | dig "kof-mothership" "values" "cert-manager" "cluster-issuer" "create" false) }}
          {{- $values = mergeOverwrite $values (`
          storage:
            cert-manager:
              cluster-issuer:
                create: false
          ` | fromYaml) }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- if eq $component "kof-child" }}
      {{- $values = mergeOverwrite $values (dict "autoUpgrade" $.Values.autoUpgrade) }}

      {{- $m2m := $values.fromManagement.toManagementCluster.enabled | ternary 1 0 }}
      {{- $m2r := $values.fromManagement.toRegionalCluster.name | any | ternary 1 0 }}
      {{- $regionless := $.Values.regionless.enabled | ternary 1 0 }}
      {{- if gt (add $m2m $m2r $regionless) 1 }}
        {{- fail "Only one of `regionless.enabled`, `kof-child.values.fromManagement.toManagementCluster.enabled`, and `kof-child.values.fromManagement.toRegionalCluster.name` can be enabled at the same time" }}
      {{- end }}

      {{- if $.Values.tls.insecureSkipVerify }}
        {{- $values = mergeOverwrite $values (`
        collectors:
          opentelemetry-kube-stack:
            defaultCRConfig:
              config:
                exporters:
                  otlphttp/logs:
                    tls:
                      insecure_skip_verify: true
                  otlphttp/logs-audit:
                    tls:
                      insecure_skip_verify: true
                  prometheusremotewrite:
                    tls:
                      insecure_skip_verify: true
                  otlphttp/traces:
                    tls:
                      insecure_skip_verify: true
          opencost:
            opencost:
              prometheus:
                insecureSkipVerify: true
        ` | fromYaml) }}
      {{- end }}
    {{- end }}

    {{- $values | toYaml | nindent 4 }}
{{- end }}
{{- end }}
