---
{{- if .Values.global.helmRepo.kofManaged.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .Values.global.helmRepo.name }}
  namespace: {{ .Values.global.helmRepo.namespace }}
  labels:
    {{- include "kof.labels" . | nindent 4 }}
spec:
  {{- with .Values.global.helmRepo.kofManaged }}
  insecure: {{ .insecure }}
  type: {{ .type }}
  url: {{ .url }}
  {{- end }}
  interval: {{ .Values.global.helmRepo.interval }}
  {{- with .Values.global.helmRepo.spec }}{{ . | toYaml | nindent 2 }}{{ end }}
{{- end }}
{{- if index .Values "victoria-metrics-operator" "enabled" }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: {{ .Values.global.helmRepo.namespace }}
  labels:
    {{- include "kof.labels" . | nindent 4 }}
spec:
  {{- with index .Values "victoria-metrics-operator" "repo" }}
  type: {{ .type }}
  url: {{ .url }}
  {{- end }}
  interval: {{ .Values.global.helmRepo.interval }}
  {{- with .Values.global.helmRepo.spec }}{{ . | toYaml | nindent 2 }}{{ end }}
{{- end }}
