{{- range $component := append .Values.global.components "victoria-metrics-operator" }}
{{- if index $.Values $component "enabled" }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $component }}
  namespace: {{ include "kof.namespace" $ }}
  annotations:
    reconcile.fluxcd.io/requestedAt: "{{ now | unixEpoch }}"
    reconcile.fluxcd.io/forceAt: "{{ now | unixEpoch }}"
    helm.sh/resource-policy: keep # FluxCD is unable to delete all releases in the correct order
  labels:
    {{- include "kof.labels" $ | nindent 4 }}
    k0rdent.mirantis.com/component: {{ $component }}
spec:
  interval: {{ $.Values.flux.timeout }}
  timeout: {{ $.Values.flux.timeout }}
  {{- with index $.Values $component "dependsOn" }}
  dependsOn:
    {{- range $dep := . }}
    {{- if index $.Values $dep "enabled" }}
    - name: {{ $dep }}
      namespace: {{ include "kof.namespace" $ }}
    {{- end }}
    {{- end }}
  {{- end }}
  chartRef:
    kind: HelmChart
    name: {{ $component }}
    namespace: {{ $.Values.global.helmRepo.namespace }}
  install:
    createNamespace: {{ $.Values.flux.install.createNamespace  }}
    remediation:
      retries: {{ $.Values.flux.install.remediation.retries }}
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: {{ $.Values.flux.upgrade.retryInterval }}
  values:
    {{- $values := mergeOverwrite (dict) (index $.Values $component "values") }}

    {{- if eq $component "kof-mothership" }}
      {{- $values = mergeOverwrite $values (print `
      kcm:
        kof:
          repo:
            name: ` $.Values.global.helmRepo.name | fromYaml) }}

      {{- if $.Values.regionless.enabled }}
        {{- $values = mergeOverwrite $values (print `
        # Passing values to kof-operator.
        regionless:
          enabled: true
          domain: ` (quote $.Values.regionless.domain) `
          httpConfig: ` (quote $.Values.regionless.httpConfig) `

        # Management cluster name.
        global:
          clusterName: ` (quote $.Values.regionless.clusterName) `
        kof-dashboards:
          grafana:
            dashboard:
              datasource:
                filters:
                  cluster: ` (quote $.Values.regionless.clusterName) `

        # Using the Gateway for vmauth from kof-storage, not from kof-mothership.
        gateway:
          enabled: false

        # Using VMCluster from kof-storage, but VMAlertManager - from kof-mothership.
        victoriametrics:
          vmcluster:
            enabled: false
        ` | fromYaml) }}
      {{- end }}
    {{- end }}

    {{- if and (eq $component "victoria-metrics-operator") $.Values.regionless.enabled }}
      {{- $values = mergeOverwrite $values (`
      # Using VM-operator from kof umbrella as required for kof-mothership,
      # just enabling Gateway API for regionless.
      env:
        - name: VM_GATEWAY_API_ENABLED
          value: "true"
      ` | fromYaml) }}
    {{- end }}

    {{- if and (eq $component "kof-regional") $.Values.regionless.enabled }}
      {{- $values = mergeOverwrite $values (print `
      # Using VM-operator and kof-operators from kof umbrella, not from kof-regional MCS.
      victoria-metrics-operator:
        enabled: false
      kof-operators:
        enabled: false

      # Using cert-manager installed to mgmt cluster by KCM, it has enableGatewayAPI.
      cert-manager:
        enabled: false

      # Switch MCS to the regionless setup.
      regionless:
        enabled: true
        clusterName: ` (quote $.Values.regionless.clusterName) `
        domain: ` (quote $.Values.regionless.domain) `
      ` | fromYaml) }}
    {{- end }}

    {{- $values | toYaml | nindent 4 }}
{{- end }}
{{- end }}
