{{- if .Values.istio.enabled }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: kof-namespace
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: member
  serviceSpec:
    services:
      - name: kof-namespace
        namespace: {{ .Values.kcm.namespace }}
        template: kof-propagation-{{ $.Chart.Version | replace "." "-" }}
        values: |
          propagation:
            enabled: true
            data: |
              kind: Namespace
              apiVersion: v1
              metadata:
                name: kof
                labels:
                  istio-injection: enabled
{{- end }}