{{- if .Values.istio.enabled }}
{{- $prefix := "kof-namespace" }}
{{- $newName := printf "%s-%s" $prefix ($.Chart.Version | replace "." "-") }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: {{ $newName }}
  namespace: {{ .Values.kcm.namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    localSourceRef:
      kind: ConfigMap
      name: kof-namespace-template
      namespace: {{ .Values.kcm.namespace }}
    deploymentType: Remote
    path: ""
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplateChain
metadata:
  name: {{ $newName }}
  namespace: {{ .Values.kcm.namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  supportedTemplates:
    - name: {{ $newName }}
    {{- range $template := (lookup
      "k0rdent.mirantis.com/v1beta1" "ServiceTemplate"
      $.Values.kcm.namespace ""
    ).items }}
      {{- $oldName := $template.metadata.name }}
      {{- if and ($oldName | hasPrefix $prefix) (ne $oldName $newName) $template.spec.resources }}
    - name: {{ $oldName }}
      availableUpgrades:
        - name: {{ $newName }}
          version: {{ $.Chart.Version | quote }}
      {{- end }}
    {{- end }}
{{- end }}