export const METRICS = {
  OTEL_SCOPE_INFO: "otel_scope_info",
  OTELCOL_EXPORTER_PROM_WRITE_CONSUMERS: "otelcol_exporter_prometheusremotewrite_consumers",
  OTELCOL_EXPORTER_PROM_WRITE_SENT_BATCHES: "otelcol_exporter_prometheusremotewrite_sent_batches_total",
  OTELCOL_EXPORTER_PROM_WRITE_TRANS_RATIO: "otelcol_exporter_prometheusremotewrite_translated_time_series_ratio_total",
  OTELCOL_EXPORTER_QUEUE_CAPACITY: "otelcol_exporter_queue_capacity",
  OTELCOL_EXPORTER_QUEUE_SIZE: "otelcol_exporter_queue_size",
  OTELCOL_EXPORTER_SEND_FAILED_LOG_RECORDS: "otelcol_exporter_send_failed_log_records_total",
  OTELCOL_EXPORTER_SEND_FAILED_METRIC_POINTS: "otelcol_exporter_send_failed_metric_points_total",
  OTELCOL_EXPORTER_SENT_LOG_RECORDS: "otelcol_exporter_sent_log_records_total",
  OTELCOL_EXPORTER_SENT_METRIC_POINTS: "otelcol_exporter_sent_metric_points_total",
  OTELCOL_FILECONSUMER_OPEN_FILES: "otelcol_fileconsumer_open_files_ratio",
  OTELCOL_FILECONSUMER_READING_FILES: "otelcol_fileconsumer_reading_files_ratio",
  OTELCOL_OTELSVC_K8S_POD_ADDED: "otelcol_otelsvc_k8s_pod_added_ratio_total",
  OTELCOL_OTELSVC_K8S_POD_TABLE_SIZE: "otelcol_otelsvc_k8s_pod_table_size_ratio",
  OTELCOL_OTELSVC_K8S_POD_UPDATED: "otelcol_otelsvc_k8s_pod_updated_ratio_total",
  OTELCOL_PROCESS_CPU_SECONDS: "otelcol_process_cpu_seconds_total",
  OTELCOL_PROCESS_MEMORY_RSS: "otelcol_process_memory_rss_bytes",
  OTELCOL_PROCESS_RUNTIME_HEAP_ALLOC: "otelcol_process_runtime_heap_alloc_bytes",
  OTELCOL_PROCESS_RUNTIME_TOTAL_ALLOC: "otelcol_process_runtime_total_alloc_bytes_total",
  OTELCOL_PROCESS_RUNTIME_TOTAL_SYS_MEMORY: "otelcol_process_runtime_total_sys_memory_bytes",
  OTELCOL_PROCESS_UPTIME_SECONDS: "otelcol_process_uptime_seconds_total",
  OTELCOL_PROCESSOR_BATCH_SEND_SIZE: "otelcol_processor_batch_batch_send_size",
  OTELCOL_PROCESSOR_BATCH_SIZE_TRIGGER_SEND: "otelcol_processor_batch_batch_size_trigger_send_total",
  OTELCOL_PROCESSOR_BATCH_METADATA_CARDINALITY: "otelcol_processor_batch_metadata_cardinality",
  OTELCOL_PROCESSOR_BATCH_TIMEOUT_TRIGGER_SEND: "otelcol_processor_batch_timeout_trigger_send_total",
  OTELCOL_PROCESSOR_INCOMING_ITEMS: "otelcol_processor_incoming_items_total",
  OTELCOL_PROCESSOR_OUTGOING_ITEMS: "otelcol_processor_outgoing_items_total",
  OTELCOL_RECEIVER_ACCEPTED_LOG_RECORDS: "otelcol_receiver_accepted_log_records_total",
  OTELCOL_RECEIVER_ACCEPTED_METRIC_POINTS: "otelcol_receiver_accepted_metric_points_total",
  OTELCOL_RECEIVER_REFUSED_LOG_RECORDS: "otelcol_receiver_refused_log_records_total",
  OTELCOL_RECEIVER_REFUSED_METRIC_POINTS: "otelcol_receiver_refused_metric_points_total",
  CONDITION_READY_HEALTHY: "condition_ready_healthy",
  CONDITION_READY_MESSAGE: "condition_ready_message",
  CONDITION_READY_REASON: "condition_ready_reason",
  CONTAINER_RESOURCE_CPU_LIMIT: "container_resource_cpu_limit",
  CONTAINER_RESOURCE_CPU_USAGE: "container_resource_cpu_usage",
  CONTAINER_RESOURCE_MEMORY_LIMIT: "container_resource_memory_limit",
  CONTAINER_RESOURCE_MEMORY_USAGE: "container_resource_memory_usage",
  PROMHTTP_METRIC_HANDLER_ERRORS: "promhttp_metric_handler_errors_total",
  TARGET_INFO: "target_info",
} as const;

export const VICTORIA_METRICS = {
  VM_HTTP_REQUESTS_TOTAL: "vm_http_requests_total",
  VM_HTTP_REQUESTS_ALL_TOTAL: "vm_http_requests_all_total",
  VM_HTTP_REQUEST_DURATION_SECONDS_SUM:"vm_http_request_duration_seconds_sum",
  VM_HTTP_REQUEST_DURATION_SECONDS_COUNT: "vm_http_request_duration_seconds_count",
  VM_HTTP_REQUEST_ERRORS_TOTAL: "vm_http_request_errors_total",
  VM_HTTP_CONN_TIMEOUT_CLOSED_CONNS_TOTAL: "vm_http_conn_timeout_closed_conns_total",
  VM_TCPLISTENER_CONNS: "vm_tcplistener_conns",
  VM_TCPLISTENER_READ_BYTES_TOTAL: "vm_tcplistener_read_bytes_total",
  VM_TCPLISTENER_WRITE_BYTES_TOTAL: "vm_tcplistener_written_bytes_total",
  VM_TCPLISTENER_ERRORS_TOTAL: "vm_tcplistener_errors_total",
  VM_TCPLISTENER_ACCEPTS_TOTAL: "vm_tcplistener_accepts_total",
  VM_TCPLISTENER_WRITTEN_BYTES_TOTAL: "vm_tcplistener_written_bytes_total",
  VM_TCPLISTENER_READ_TIMEOUTS_TOTAL: "vm_tcplistener_read_timeouts_total",
  VM_AVAILABLE_CPU_CORES: "vm_available_cpu_cores",
  VL_ERRORS_TOTAL: "vl_errors_total",
  VL_HTTP_ERRORS_TOTAL: "vl_http_errors_total",
  VL_UDP_ERRORS_TOTAL: "vl_udp_errors_total",
  VL_HTTP_REQUESTS_TOTAL: "vl_http_requests_total",
  VL_HTTP_REQUEST_DURATION_SECONDS_SUM: "vl_http_request_duration_seconds_sum",
  VL_UDP_REQESTS_TOTAL: "vl_udp_reqests_total",

  VL_DATA_SIZE_BYTES: "vl_data_size_bytes",
  VL_STORAGE_ROWS: "vl_storage_rows",
  
  VL_ROWS_INGESTED_TOTAL: "vl_rows_ingested_total",
  VL_BYTES_INGESTED_TOTAL: "vl_bytes_ingested_total",
  VL_STREAM_CREATED_TOTAL: "vl_streams_created_total",
  
  VL_ACTIVE_FORCE_MERGES: "vl_active_force_merges",
  VL_MERGES_TOTAL: "vl_merges_total",
  VL_ROWS_DROPPED_TOTAL: "vl_rows_dropped_total",
  VL_TOO_LONG_LINES_SKIPPED_TOTAL: "vl_too_long_lines_skipped_total",


  PROCESS_IO_READ_BYTES_TOTAL: "process_io_read_bytes_total",
  PROCESS_IO_WRITTEN_BYTES_TOTAL: "process_io_written_bytes_total",
  PROCESS_IO_READ_SYSCALLS_TOTAL: "process_io_read_syscalls_total",
  PROCESS_IO_WRITE_SYSCALLS_TOTAL: "process_io_write_syscalls_total",
  PROCESS_CPU_SECONDS_TOTAL: "process_cpu_seconds_total",
  PROCESS_CPU_SECONDS_USER_TOTAL: "process_cpu_seconds_user_total",
  PROCESS_CPU_SECONDS_SYSTEM_TOTAL: "process_cpu_seconds_system_total",
  PROCESS_RESIDENT_MEMORY_BYTES: "process_resident_memory_bytes",
  PROCESS_VIRTUAL_MEMORY_BYTES: "process_virtual_memory_bytes",
  PROCESS_MEMORY_LIMIT_BYTES: "process_memory_limit_bytes",
  PROCESS_RESIDENT_MEMORY_PEAK_BYTES: "process_resident_memory_peak_bytes",
  GO_GOROUTINES: "go_goroutines",
  GO_CGO_CALLS_COUNT: "go_cgo_calls_count",
  GO_GOMAXPROCES: "go_gomaxprocs",
  GO_GC_CPU_SECONDS_TOTAL: "go_gc_cpu_seconds_total",
  GO_GC_DURATION_SECONDS: "go_gc_duration_seconds",
  GO_GC_DURATION_SECONDS_COUNT: "go_gc_duration_seconds_count",
  GO_MEMSTATS_HEAP_ALLOC_BYTES: "go_memstats_heap_alloc_bytes",
  GO_MEMSTATS_HEAP_INUSE_BYTES: "go_memstats_heap_inuse_bytes",
  GO_MEMSTATS_HEAP_IDLE_BYTES: "go_memstats_heap_idle_bytes",
  GO_MEMSTATS_HEAP_OBJECTS: "go_memstats_heap_objects",

  VLSELECT_BACKEND_CONNS: "vlselect_backend_conns",
  VLSELECT_BACKEND_DIALS_TOTAL: "vlselect_backend_dials_total",
  VLSELECT_BACKEND_DIAL_ERRORS_TOTAL: "vlselect_backend_dial_errors_total",
  VLSELECT_BACKEND_CONN_BYTES_READ_TOTAL: "vlselect_backend_conn_bytes_read_total",
  VLSELECT_BACKEND_CONN_BYTES_WRITTEN_TOTAL: "vlselect_backend_conn_bytes_written_total",
  VLSELECT_BACKEND_CONN_READ_ERRORS_TOTAL: "vlselect_backend_conn_read_errors_total",

  VLINSERT_BACKEND_CONNS: "vlinsert_backend_conns",
  VLINSERT_BACKEND_CONNS_BYTE_WRITTEN: "vlinsert_backend_conn_bytes_written_total",
  VLINSERT_BACKEND_CONNS_BYTE_READ: "vlinsert_backend_conn_bytes_read_total",
  VLINSERT_BACKEND_CONNS_WRITES_TOTAL: "vlinsert_backend_conn_writes_total",
  VLINSERT_BACKEND_CONNS_READS_TOTAL: "vlinsert_backend_conn_reads_total",
  VLINSERT_BACKEND_CONNS_READ_ERRORS_TOTAL: "vlinsert_backend_conn_read_errors_total",
  VLINSERT_BACKEND_CONNS_WRITE_ERRORS_TOTAL: "vlinsert_backend_conn_write_errors_total",
  VLINSERT_BACKEND_DIALS_TOTAL: "vlinsert_backend_dials_total",
  VLINSERT_BACKEND_DIALS_ERRORS_TOTAL: "vlinsert_backend_dial_errors_total",
  

  VM_RPC_ROWS_SENT_TOTAL: "vm_rpc_rows_sent_total",
  VM_RPC_ROWS_PENDING: "vm_rpc_rows_pending",
  VM_RPC_ROWS_PUSHED_TOTAL: "vm_rpc_rows_pushed_total",
  VM_ROWS_INSERTED_TOTAL: "vm_rows_inserted_total",
  VM_ROWS_INVALID_TOTAL: "vm_rows_invalid_total",
  
  VM_ROWS_PER_INSERT_SUM: "vm_rows_per_insert_sum",
  VM_ROWS_PER_INSERT_COUNT: "vm_rows_per_insert_count",
  
  VM_RPC_VMSTORAGE_IS_REACHABLE: "vm_rpc_vmstorage_is_reachable",
  VM_RPC_VMSTORAGE_IS_READ_ONLY: "vm_rpc_vmstorage_is_read_only",
  
  VM_RPC_DIAL_ERRORS_TOTAL: "vm_rpc_dial_errors_total",
  
  VM_RPC_ROWS_DROPPED_ON_OVERLOAD_TOTAL: "vm_rpc_rows_dropped_on_overload_total",
  VM_RPC_ROWS_INCOMPLETELY_REPLICATED_TOTAL: "vm_rpc_rows_incompletely_replicated_total",
  VM_RPC_REROUTES_TOTAL: "vm_rpc_reroutes_total",
  
  // VMSelect
  VM_TENANT_SELECT_REQUEST_TOTAL: "vm_tenant_select_requests_total",
  VM_METRIC_ROWS_READ_TOTAL: "vm_metric_rows_read_total",
  VM_METRICS_ROWS_SKIPPED_TOTAL: "vm_metric_rows_skipped_total",
  VM_ROWS_SCANNED_PER_QUERY_SUM: "vm_rows_scanned_per_query_sum",

  VM_TMP_BLOCK_FILES_CREATED_TOTAL: "vm_tmp_blocks_files_created_total",
  VM_TMP_BLOCK_FILES_DIRECTORY_FREE_BYTES: "vm_tmp_blocks_files_directory_free_bytes",
  VM_TMP_BLOCK_MAX_INMEMORY_FILE_SIZE_BYTES: "vm_tmp_blocks_max_inmemory_file_size_bytes",
  
  VM_ROLLUP_RESULT_CACHE_FULL_HITS_TOTAL: "vm_rollup_result_cache_full_hits_total",
  VM_ROLLUP_RESULT_CACHE_PARTIAL_HITS_TOTAL: "vm_rollup_result_cache_partial_hits_total",
  VM_ROLLUP_RESULT_CACHE_MISS_TOTAL: "vm_rollup_result_cache_miss_total",
  
  
  // VMStorage
  VM_ROWS_RECEIVED_BY_STORAGE_TOTAL: "vm_rows_received_by_storage_total",
  VM_ROWS_ADDED_TO_STORAGE_TOTAL: "vm_rows_added_to_storage_total",
  VM_ACTIVE_MERGE: "vm_active_merges",
  VM_DATA_SIZE_BYTES: "vm_data_size_bytes",

  VM_ROWS_MERGED_TOTAL: "vm_rows_merged_total",
  VM_ROWS_IGNORED_TOTAL: "vm_rows_ignored_total",
  VM_ROWS_DELETED_TOTAL: "vm_rows_deleted_total",

  
  
  
}

export type MetricName = typeof METRICS[keyof typeof METRICS];