export const METRICS = {
  OTEL_SCOPE_INFO: "otel_scope_info",
  OTELCOL_EXPORTER_PROM_WRITE_CONSUMERS: "otelcol_exporter_prometheusremotewrite_consumers",
  OTELCOL_EXPORTER_PROM_WRITE_SENT_BATCHES: "otelcol_exporter_prometheusremotewrite_sent_batches_total",
  OTELCOL_EXPORTER_PROM_WRITE_TRANS_RATIO: "otelcol_exporter_prometheusremotewrite_translated_time_series_ratio_total",
  OTELCOL_EXPORTER_QUEUE_CAPACITY: "otelcol_exporter_queue_capacity",
  OTELCOL_EXPORTER_QUEUE_SIZE: "otelcol_exporter_queue_size",
  OTELCOL_EXPORTER_SEND_FAILED_LOG_RECORDS: "otelcol_exporter_send_failed_log_records_total",
  OTELCOL_EXPORTER_SEND_FAILED_METRIC_POINTS: "otelcol_exporter_send_failed_metric_points_total",
  OTELCOL_EXPORTER_SENT_LOG_RECORDS: "otelcol_exporter_sent_log_records_total",
  OTELCOL_EXPORTER_SENT_METRIC_POINTS: "otelcol_exporter_sent_metric_points_total",
  OTELCOL_FILECONSUMER_OPEN_FILES: "otelcol_fileconsumer_open_files_ratio",
  OTELCOL_FILECONSUMER_READING_FILES: "otelcol_fileconsumer_reading_files_ratio",
  OTELCOL_OTELSVC_K8S_POD_ADDED: "otelcol_otelsvc_k8s_pod_added_ratio_total",
  OTELCOL_OTELSVC_K8S_POD_TABLE_SIZE: "otelcol_otelsvc_k8s_pod_table_size_ratio",
  OTELCOL_OTELSVC_K8S_POD_UPDATED: "otelcol_otelsvc_k8s_pod_updated_ratio_total",
  OTELCOL_PROCESS_CPU_SECONDS: "otelcol_process_cpu_seconds_total",
  OTELCOL_PROCESS_MEMORY_RSS: "otelcol_process_memory_rss_bytes",
  OTELCOL_PROCESS_RUNTIME_HEAP_ALLOC: "otelcol_process_runtime_heap_alloc_bytes",
  OTELCOL_PROCESS_RUNTIME_TOTAL_ALLOC: "otelcol_process_runtime_total_alloc_bytes_total",
  OTELCOL_PROCESS_RUNTIME_TOTAL_SYS_MEMORY: "otelcol_process_runtime_total_sys_memory_bytes",
  OTELCOL_PROCESS_UPTIME_SECONDS: "otelcol_process_uptime_seconds_total",
  OTELCOL_PROCESSOR_BATCH_SEND_SIZE: "otelcol_processor_batch_batch_send_size",
  OTELCOL_PROCESSOR_BATCH_SIZE_TRIGGER_SEND: "otelcol_processor_batch_batch_size_trigger_send_total",
  OTELCOL_PROCESSOR_BATCH_METADATA_CARDINALITY: "otelcol_processor_batch_metadata_cardinality",
  OTELCOL_PROCESSOR_BATCH_TIMEOUT_TRIGGER_SEND: "otelcol_processor_batch_timeout_trigger_send_total",
  OTELCOL_PROCESSOR_INCOMING_ITEMS: "otelcol_processor_incoming_items_total",
  OTELCOL_PROCESSOR_OUTGOING_ITEMS: "otelcol_processor_outgoing_items_total",
  OTELCOL_RECEIVER_ACCEPTED_LOG_RECORDS: "otelcol_receiver_accepted_log_records_total",
  OTELCOL_RECEIVER_ACCEPTED_METRIC_POINTS: "otelcol_receiver_accepted_metric_points_total",
  OTELCOL_RECEIVER_REFUSED_LOG_RECORDS: "otelcol_receiver_refused_log_records_total",
  OTELCOL_RECEIVER_REFUSED_METRIC_POINTS: "otelcol_receiver_refused_metric_points_total",
  OTELCOL_CONDITION_READY_HEALTHY: "condition_ready_healthy",
  OTELCOL_CONDITION_READY_MESSAGE: "condition_ready_message",
  OTELCOL_CONDITION_READY_REASON: "condition_ready_reason",
  OTELCOL_CONTAINER_RESOURCE_CPU_LIMIT: "container_resource_cpu_limit",
  OTELCOL_CONTAINER_RESOURCE_CPU_USAGE: "container_resource_cpu_usage",
  OTELCOL_CONTAINER_RESOURCE_MEMORY_LIMIT: "container_resource_memory_limit",
  OTELCOL_CONTAINER_RESOURCE_MEMORY_USAGE: "container_resource_memory_usage",
  PROMHTTP_METRIC_HANDLER_ERRORS: "promhttp_metric_handler_errors_total",
  TARGET_INFO: "target_info",
} as const;

export type MetricName = typeof METRICS[keyof typeof METRICS];