cert-manager:
  enabled: true
  template: cert-manager-1-19-3

ingress-nginx:
  enabled: false
  template: ingress-nginx-4-14-3

envoy-gateway:
  enabled: true
  template: envoy-gateway-1-3-2

gateway:
  name: gateway
  namespace: kof

# --set-file globalValues=global-values.yaml
globalValues: "{}"

collectors: {}
storage: {}
operators: {}

istio:
  # -- Installs resources required for the KOF to work properly with the main Istio chart.
  enabled: true

  dependsOn:
    - k0rdent-istio-network
