cert-manager:
  enabled: true
  template: cert-manager-v1-19-3
  cluster-issuer:
    provider: letsencrypt

ingress-nginx:
  enabled: false
  template: ingress-nginx-4-14-3

envoy-gateway:
  enabled: true
  template: gateway-helm-v1-7-1

gateway:
  name: gateway
  namespace: kof

# --set-file globalValues=global-values.yaml
globalValues: "{}"

collectors: {}
storage: {}
operators: {}

istio:
  # -- Installs resources required for the KOF to work properly with the main Istio chart.
  enabled: true

  dependsOn:
    - k0rdent-istio-network
