{{- if .Values.kcm.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kcm-controller-manager-metrics-monitor
  namespace: {{ .Values.kcm.namespace }}
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      interval: 30s
      metricRelabelings:
        - action: drop
          regex: projectsveltos_(.+)
          sourceLabels:
            - __name__
  selector: {{ .Values.kcm.serviceMonitor.selector | toYaml | nindent 4 }}
{{- end }}
