name: Fetch PR Reference
description: Gets the PR merge commit SHA and checks out the repository
runs:
  using: "composite"
  steps:
    - name: Get PR ref
      uses: actions/github-script@v7
      id: pr
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            ...context.repo,
            pull_number: context.payload.pull_request.number,
          });
          return pullRequest
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ fromJSON(steps.pr.outputs.result).merge_commit_sha }}
        fetch-depth: 0

