cert-manager:
  enabled: true
  template: cert-manager-v1-19-3

collectors:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

fromManagement:
  # -- Collect metrics/logs/traces from Management cluster and export to Regional cluster.
  toRegionalCluster:
    name: ""
    namespace: kcm-system

  # -- Additional values for kof-collectors chart deployed to Management cluster.
  collectors: {}

operators:
  grafana-operator:
    enabled: false

istio:
  # -- Installs resources required for the KOF to work properly with the main Istio chart.
  enabled: true

  dependsOn:
    - k0rdent-istio-network
