{{- if .Values.kcm.installTemplates }}
# https://github.com/k0rdent/catalog/blob/main/charts/ingress-nginx/ingress-nginx-service-template-4.11.3/templates/service-template.yaml
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: ingress-nginx-4-11-3
  namespace: {{ .Values.kcm.namespace }}
spec:
  helm:
    chartSpec:
      chart: ingress-nginx
      version: 4.11.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
{{- end }}
