apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: kof-storage-child-secret-propagation
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
  serviceSpec:
    services:
      - name: kof-vmuser-creds
        namespace: {{ .Release.Namespace }}
        template: kof-propagation-{{ $.Chart.Version | replace "." "-" }}
        values: |
          propagation:
            enabled: true
            data: |
              {{`{{ $s := getResource "secret" }}{{ $s = chainRemoveField $s "metadata.ownerReferences" }}{{ $s = chainSetField $s "metadata.namespace" "kof" }}{{ toYaml $s | nindent 14 }}`}}
    templateResourceRefs:
    - identifier: secret
      resource:
        apiVersion: v1
        kind: Secret
        name: kof-vmuser-creds-{{`{{ (printf "kof-cluster-config-%s/%s" .Cluster.metadata.name .Cluster.metadata.namespace) | adler32sum }}`}}
        namespace: {{ `"{{ .Cluster.metadata.namespace }}"` }}
