apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: kof-storage-secret-propagation
spec:
  clusterSelector:
    matchExpressions:
      - key: k0rdent.mirantis.com/kof-cluster-role
        operator: Exists
  serviceSpec:
    services:
      - name: storage-secret-propagation
        namespace: {{ .Values.kcm.namespace }}
        template: kof-secret-propagation
    templateResourceRefs:
    - identifier: secret
      resource:
        apiVersion: v1
        kind: Secret
        name: kof-vmuser-creds-{{`{{ (printf "kof-cluster-config-%s" .Cluster.metadata.name) | adler32sum }}`}}
        namespace: {{ .Release.Namespace }}