apiVersion: v1
data:
  value: ${KUBECONFIG_DATA}
kind: Secret
metadata:
  name: ${KIND_CLUSTER_NAME}-kubeconf
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: ${KIND_CLUSTER_NAME}-cred
  namespace: ${NAMESPACE}
spec:
  description: Adopted ${KIND_CLUSTER_NAME} cluster credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: ${KIND_CLUSTER_NAME}-kubeconf
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adopted-cluster-kubeconf-resource-template
  name: ${KIND_CLUSTER_NAME}-kubeconf-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
