name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into the runner image eventually.
runs:
  using: composite
  steps:
    # - name: Install required packages
    #   shell: bash --noprofile --norc -euo pipefail {0}
    #   run: |
    #     echo "::group::apt"
    #     sudo apt update -qq
    #     sudo apt install -qqy build-essential wget
    #     echo "::endgroup::"

    - name: Set shared env vars
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        KCM_NEXT_RELEASE=main
        echo "KCM_NEXT_RELEASE=$KCM_NEXT_RELEASE" >> "$GITHUB_ENV"
        echo "BASE_COMMIT=origin/$KCM_NEXT_RELEASE" >> "$GITHUB_ENV"
        echo "HEAD_COMMIT=origin/$KCM_NEXT_RELEASE" >> "$GITHUB_ENV"

    - uses: azure/setup-kubectl@v4

    - uses: actions/setup-node@v6
      with:
        node-version: "18.18.2"
