from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml


@dataclass(frozen=True)
class ExpectedDashboard:
    """A single dashboard expected to exist in Grafana."""

    name: str
    title: str
    category: str
    source_file: str


class DashboardReference:
    """Expected Grafana dashboard inventory loaded from the static reference file.

    The reference file is generated by `scripts/generate_reference.py` and
    contains all dashboards that should exist after a KOF installation.

    Dashboards with `rendered: false` are excluded — these exist as chart
    source files but do not produce GrafanaDashboard resources (e.g.,
    conditional dashboards disabled by default values).
    """

    def __init__(self, dashboards: list[ExpectedDashboard]) -> None:
        self._dashboards = tuple(dashboards)

    @property
    def titles(self) -> tuple[str, ...]:
        """All expected dashboard titles (used for inventory comparison)."""
        return tuple(d.title for d in self._dashboards)

    @property
    def count(self) -> int:
        return len(self._dashboards)

    @classmethod
    def load(cls, path: Path) -> DashboardReference:
        """Load reference from a YAML file.

        Raises:
            FileNotFoundError: if path doesn't exist.
            ValueError: if the file is malformed.
        """
        if not path.exists():
            raise FileNotFoundError(
                f"Dashboard reference file not found: {path}\n"
                f"Generate it with: make generate-reference"
            )

        with path.open() as f:
            data = yaml.safe_load(f)

        if not isinstance(data, dict) or "dashboards" not in data:
            raise ValueError(
                f"Invalid reference file format: {path}\n"
                f"Expected a YAML file with a 'dashboards' key. "
                f"Regenerate with: make generate-reference"
            )

        dashboards: list[ExpectedDashboard] = []
        for item in data["dashboards"]:
            if not isinstance(item, dict):
                continue
            # Skip dashboards that are not rendered as GrafanaDashboard resources
            if not item.get("rendered", True):
                continue
            dashboards.append(
                ExpectedDashboard(
                    name=str(item.get("name", "")),
                    title=str(item.get("title") or item.get("name", "")),
                    category=str(item.get("category", "")),
                    source_file=str(item.get("file", "")),
                )
            )

        if not dashboards:
            raise ValueError(
                f"No rendered dashboards found in {path}. "
                f"The reference file may be empty or corrupted. "
                f"Regenerate with: make generate-reference"
            )

        return cls(dashboards)
