{
 "title": "Kubernetes Events",
 "description": "Kubernetes Events",
 "tags": [
  "Logs",
  "Kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "datasource",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "namespace", "label": "namespace", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Kubernetes Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*"
    }
   ]
  },
  { "title": "Kubernetes Events - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*\n| stats by (type) count()",
     "legendFormat": "{{`{{type}}`}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*\ntype:=\"Warning\"\n| stats count()",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"Failed\"\n_msg:~\"ImagePullBackOff\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Liveness Probe Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"Killing\"\n_msg:~\"failed liveness probe\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Volume Mount Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"FailedMount\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Scheduling Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"FailedScheduling\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"OOMKilling\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"BackOff\"\n| stats count()\n"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"TaintManagerEviction\"\n_msg:~\"Marking for deletion Pod\"\n| stats count()"
    }
   ]
  },
  {
   "title": "System OOM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nreason:=\"SystemOOM\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Kubernetes Events - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Events by Reason",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*\n| stats by (reason) count()",
     "legendFormat": "{{`{{reason}}`}}"
    }
   ]
  },
  {
   "title": "Events by Namespace",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*\n| stats by (k8s.namespace.name) count()",
     "legendFormat": "{{`{{k8s.namespace.name}}`}}"
    }
   ]
  },
  {
   "title": "Events by Source",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*\n| unpack_json from regarding result_prefix \"regarding_\"\n| stats by (regarding_name) count()",
     "legendFormat": "{{`{{regarding_name}}`}}"
    }
   ]
  },
  {
   "title": "Events by Kind",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*\n| unpack_json from regarding result_prefix \"regarding_\"\n| stats by (regarding_kind) count()",
     "legendFormat": "{{`{{regarding_kind}}`}}"
    }
   ]
  },
  { "title": "Kubernetes Events - Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\"$namespace\"\nevent.name:*"
    }
   ]
  }
 ]
}