{
 "title": "Cluster Deployments Events",
 "description": "Cluster Deployments Events",
 "tags": [
  "Logs",
  "Kubernetes",
  "Events"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "datasource",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "cluster_deployment",
    "label": "cluster_deployment",
    "query": {
     "query": "regarding:~\"ClusterDeployment\""
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "regarding:~\"$cluster_deployment\""
    }
   },
   {
    "name": "linked_object",
    "label": "linked_object",
    "query": {
     "query": "regarding:~\"$cluster_deployment\""
    }
   },
   {
    "name": "generation",
    "label": "generation",
    "query": {
     "query": "regarding:~\"$cluster_deployment\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Deployments Events - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "k8s.namespace.name:in($namespace)\n| unpack_json from regarding result_prefix \"regarding_\"\n| unpack_json from metadata result_prefix \"metadata_\"\n| regarding_kind:in($linked_object)\n| regarding_name:~\"^${cluster_deployment}(-md-.*|-cp-.*)?$\"\n| metadata_annotations.generation:in($generation)"
    }
   ]
  },
  { "title": "Cluster Deployments - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "k8s.namespace.name:in($namespace)\n| unpack_json from regarding result_prefix \"regarding_\"\n| unpack_json from metadata result_prefix \"metadata_\"\n| regarding_name:~\"^${cluster_deployment}(-md-.*|-cp-.*)?$\"\n| regarding_kind:in($linked_object)\n| metadata_annotations.generation:in($generation)\n| stats by (type) count()",
     "legendFormat": "{{`{{type}}`}}"
    }
   ]
  },
  {
   "title": "Events by Reason",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.namespace.name:in($namespace)\n| unpack_json from regarding result_prefix \"regarding_\"\n| unpack_json from metadata result_prefix \"metadata_\"\n| regarding_kind:in($linked_object)\n| regarding_name:~\"^${cluster_deployment}(-md-.*|-cp-.*)?$\"\n| metadata_annotations.generation:in($generation)\n| stats by (reason) count()",
     "legendFormat": "{{`{{reason}}`}}"
    }
   ]
  },
  { "title": "Kubernetes Events - Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "k8s.namespace.name:in($namespace)\n| unpack_json from regarding result_prefix \"regarding_\"\n| unpack_json from metadata result_prefix \"metadata_\"\n| regarding_kind:in($linked_object)\n| regarding_name:~\"^${cluster_deployment}(-md-.*|-cp-.*)?$\"\n| metadata_annotations.generation:in($generation)"
    }
   ]
  }
 ]
}