{
 "title": "k0smotron Control Plane",
 "description": "Built from https://github.com/kubernetes-monitoring/kubernetes-mixin",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\".*k0smotron.*\"},job)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"$job\"}, {{$.Values.global.clusterLabel}})"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{pod=~\".*k0smotron.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "k0smotron Controller - $pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "k0smotron Providers",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\",pod!~\"kcm.*\"}"
    }
   ]
  },
  {
   "title": "Cluster API",
   "type": "text",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "\nThis dashboard aims to present state of the service following \n[The Four Golden Signals](https://sre.google/sre-book/monitoring-distributed-systems/) principle"
   }
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"2..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"3..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"4..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"5..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\", pod=\"$pod\"}[$__rate_interval])) by (controller, result)",
     "legendFormat": "{{\"{{\"}}controller}} - {{\"{{\"}}result}}"
    }
   ]
  },
  {
   "title": "Controller Webhook Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{ {{$.Values.global.clusterLabel}}=\"$cluster\",job=\"$job\",pod=\"$pod\"}[$__rate_interval])) by (webhook, code)",
     "legendFormat": "{{\"{{\"}}webhook}} - {{\"{{\"}}code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Controller Reconciliation Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\", pod=\"$pod\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{\"{{\"}}controller}}"
    }
   ]
  },
  {
   "title": "Kube API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"5..\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Controller Webhook requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_in_flight{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\",pod=\"$pod\"}[$__rate_interval])) by (webhook)",
     "legendFormat": "{{\"{{\"}}webhook}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\"}",
     "legendFormat": "{{\"{{\"}}pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{\"{{\"}}pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{ {{$.Values.global.clusterLabel}}=\"$cluster\", job=\"$job\"}",
     "legendFormat": "{{\"{{\"}}pod}}"
    }
   ]
  }
 ]
}