{{- if .Values.jaeger.enabled }}
{{- if .Values.jaeger.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.jaeger.ingress.queryHost | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-jaeger-query
            port:
              number: 16686
        path: /
        pathType: Prefix
  tls:
  - secretName: jaeger-query-tls-secret
    hosts:
      - {{ .Values.jaeger.ingress.queryHost | quote }}
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-collector-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.jaeger.ingress.collectorHost | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-jaeger-collector
            port:
              number: 4318
        path: /
        pathType: Prefix
  tls:
  - secretName: jaeger-collector-tls-secret
    hosts:
      - {{ .Values.jaeger.ingress.collectorHost | quote }}
{{- end }}
{{- end }}