#!/usr/bin/env python3
"""KOF Observability Reference Dataset Generator.

Generates a complete static reference dataset describing what SHOULD exist
after a KOF installation. Uses rendered Helm manifests as the primary source.

Output files (tests/reference/):
  - index.yaml              Summary counts across all files
  - dashboards.yaml         Dashboard names, folders, panels, queries
  - metrics.yaml            All referenced metrics with classification
  - alerts.yaml             PrometheusRule alert definitions
  - recording_rules.yaml    PrometheusRule recording rules
  - datasources.yaml        GrafanaDatasource resources
  - collectors.yaml         OTel collector pipelines
  - service_monitors.yaml   ServiceMonitor/PodMonitor definitions
  - logs.yaml               Log pipeline topology
  - traces.yaml             Trace pipeline topology
  - kubernetes_resources.yaml  Expected K8s resource inventory

This is a STATIC reference — it describes expected state, not proof of runtime data flow.
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError as exc:
    raise SystemExit(
        "PyYAML is required. Install script dependencies with "
        "`python3 -m pip install -r scripts/requirements.txt`, or run with "
        "a Python environment that already has PyYAML."
    ) from exc

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
CHARTS_DIR = REPO_ROOT / "charts"
DASHBOARDS_DIR = CHARTS_DIR / "kof-dashboards" / "files" / "dashboards"
OUTPUT_DIR = REPO_ROOT / "tests" / "reference"

# Charts to render with helm template
HELM_CHARTS = [
    {
        "name": "kof-mothership",
        "path": CHARTS_DIR / "kof-mothership",
        "namespace": "kof",
        "set": ["grafana.enabled=true"],
    },
    {
        "name": "kof-dashboards",
        "path": CHARTS_DIR / "kof-dashboards",
        "namespace": "kof",
        "set": [],
    },
    {
        "name": "kof-collectors",
        "path": CHARTS_DIR / "kof-collectors",
        "namespace": "kof",
        "set": [],
    },
    {
        "name": "kof-storage",
        "path": CHARTS_DIR / "kof-storage",
        "namespace": "kof",
        # Avoid lookup-dependent failures when the VMUser credentials secret is
        # not present in the local chart-rendering environment.
        "set": ["global.lint=true"],
    },
    {
        "name": "kof-regional",
        "path": CHARTS_DIR / "kof-regional",
        "namespace": "kof",
        "set": [],
    },
    {
        "name": "kof-child",
        "path": CHARTS_DIR / "kof-child",
        "namespace": "kof",
        "set": [],
    },
]

# Resource kinds relevant to KOF observability
OBSERVABILITY_KINDS = {
    "GrafanaDashboard",
    "GrafanaDatasource",
    "PrometheusRule",
    "ServiceMonitor",
    "PodMonitor",
    "OpenTelemetryCollector",
    "Instrumentation",
    "VMCluster",
    "VMAlert",
    "VMAlertmanager",
    "VMAuth",
    "VMUser",
    "PromxyServerGroup",
}

# All kinds we track in kubernetes_resources.yaml
ALL_TRACKED_KINDS = OBSERVABILITY_KINDS | {
    "ServiceTemplate",
    "ServiceTemplateChain",
    "MultiClusterService",
    "HelmRepository",
    "CustomResourceDefinition",
    "Deployment",
    "DaemonSet",
    "Service",
    "ConfigMap",
    "Secret",
    "ServiceAccount",
    "ClusterRole",
    "ClusterRoleBinding",
    "Job",
}

# Critical runtime metrics that MUST be present for KOF to function
CRITICAL_RUNTIME_METRICS = [
    "up",
    "node_cpu_seconds_total",
    "node_memory_MemAvailable_bytes",
    "container_cpu_usage_seconds_total",
    "container_memory_working_set_bytes",
    "kube_pod_info",
    "kube_pod_status_phase",
    "kube_node_info",
    "kube_deployment_status_replicas_available",
    "kubelet_volume_stats_available_bytes",
    "vm_app_uptime_seconds",
    "alertmanager_config_last_reload_successful",
]

YAML_HEADER = """\
# Auto-generated by scripts/generate_reference.py
# Do not edit manually. Regenerate with: make generate-reference
#
# This is a STATIC reference dataset describing what SHOULD exist after
# a KOF installation. It does NOT prove that runtime data is flowing.
# Use live validation tests to verify actual observability pipeline health.
---
"""

# ---------------------------------------------------------------------------
# Helm Template Rendering
# ---------------------------------------------------------------------------


def helm_template(chart: dict) -> list[dict]:
    """Run helm template and return parsed YAML documents."""
    cmd = ["helm", "template", chart["name"], str(chart["path"]),
           "--namespace", chart["namespace"]]
    for s in chart.get("set", []):
        cmd.extend(["--set", s])

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
            check=True,
        )
    except FileNotFoundError as e:
        raise RuntimeError("helm binary was not found in PATH") from e
    except subprocess.TimeoutExpired as e:
        raise RuntimeError(f"helm template timed out for {chart['name']}") from e
    except subprocess.CalledProcessError as e:
        stderr = (e.stderr or "").strip()
        stdout = (e.stdout or "").strip()
        details = stderr or stdout or "no output"
        raise RuntimeError(
            f"helm template failed for {chart['name']}.\n"
            f"Command: {' '.join(cmd)}\n"
            f"Output:\n{details}"
        ) from e

    docs = []
    for doc in yaml.safe_load_all(result.stdout):
        if doc and isinstance(doc, dict):
            docs.append(doc)
    return docs


def render_all_charts() -> list[dict]:
    """Render all configured charts and return combined documents."""
    all_docs = []
    for chart in HELM_CHARTS:
        print(f"  rendering {chart['name']}...")
        docs = helm_template(chart)
        # Tag each doc with source chart
        for doc in docs:
            doc.setdefault("_source_chart", chart["name"])
        all_docs.extend(docs)
        print(f"    -> {len(docs)} resources")
    return all_docs


def get_resources_by_kind(docs: list[dict], kind: str) -> list[dict]:
    """Filter rendered documents by kind."""
    return [d for d in docs if d.get("kind") == kind]


# ---------------------------------------------------------------------------
# PromQL Metric Extraction
# ---------------------------------------------------------------------------


def extract_metrics_from_expr(expr: str) -> list[str]:
    """Extract metric names from a PromQL expression."""
    if not expr:
        return []
    # Strategy: match identifiers followed by { or ( or end-of-context
    # that appear OUTSIDE of label matchers (inside {})
    # First, remove everything inside {} to avoid matching label names/values
    no_braces = re.sub(r'\{[^}]*\}', '{}', expr)
    # Remove string literals
    no_braces = re.sub(r'"[^"]*"', '""', no_braces)
    no_braces = re.sub(r"'[^']*'", "''", no_braces)
    # Remove backtick literals
    no_braces = re.sub(r'`[^`]*`', '``', no_braces)

    # Match metric names: identifiers followed by { or ( or whitespace/operator
    metrics = re.findall(r'([a-zA-Z_:][a-zA-Z0-9_:]*)\s*(?:\{|\(|$|[\s,)\]])', no_braces)

    # Filter PromQL functions/keywords
    promql_keywords = {
        'sum', 'avg', 'min', 'max', 'count', 'stddev', 'stdvar',
        'topk', 'bottomk', 'quantile', 'count_values',
        'rate', 'irate', 'increase', 'delta', 'idelta',
        'histogram_quantile', 'histogram_avg', 'histogram_count',
        'label_replace', 'label_join',
        'abs', 'absent', 'absent_over_time', 'ceil', 'floor', 'round',
        'changes', 'clamp', 'clamp_max', 'clamp_min',
        'deriv', 'exp', 'ln', 'log2', 'log10', 'sqrt',
        'predict_linear', 'resets', 'sort', 'sort_desc',
        'time', 'timestamp', 'vector', 'scalar',
        'on', 'ignoring', 'group_left', 'group_right',
        'by', 'without', 'unless', 'and', 'or', 'offset',
        'bool', 'inf', 'nan',
        'avg_over_time', 'min_over_time', 'max_over_time',
        'sum_over_time', 'count_over_time', 'stddev_over_time',
        'last_over_time', 'present_over_time', 'quantile_over_time',
        'sgn', 'deg', 'rad', 'acos', 'asin', 'atan', 'cos', 'sin', 'tan',
        'days_in_month', 'day_of_month', 'day_of_week', 'day_of_year',
        'hour', 'minute', 'month', 'year', 'group', 'pi',
        'TMPL',  # template placeholder
    }
    # Common label names/values that are NOT metrics
    not_metrics = {
        'cpu', 'memory', 'job', 'node', 'pod', 'container', 'namespace',
        'service', 'instance', 'name', 'type', 'mode', 'key', 'url',
        'cluster', 'severity', 'alertname', 'alertstate', 'endpoint',
        'resource', 'device', 'mountpoint', 'fstype', 'le',
        'quantile', 'reason', 'condition', 'status', 'phase',
        'TMPL', 'true', 'false', 'null',
        # Grafana variables
        '__interval', '__rate_interval', '__auto',
        # LogQL / VictoriaLogs fields
        '_msg', '_time', '_stream',
    }
    return sorted(set(
        m for m in metrics
        if m.lower() not in promql_keywords
        and m not in not_metrics
        and not m.startswith('$')
        and not m.startswith('__')
        and (len(m) > 3 or m == 'up')  # skip 1-3 char tokens (label values)
    ))


# ---------------------------------------------------------------------------
# Dashboard Parsing (from raw chart files — dashboards contain Go templates)
# ---------------------------------------------------------------------------


def strip_go_templates(text: str) -> str:
    """Remove Go template expressions so YAML can be parsed."""
    text = re.sub(r'\{\{`', '', text)
    text = re.sub(r'`\}\}', '', text)
    text = re.sub(r'\{\{-?\s*/\*.*?\*/\s*-?\}\}', '', text, flags=re.DOTALL)
    text = re.sub(r'^[ \t]*\{\{-?.*?-?\}\}[ \t]*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\{\{.*?\}\}', 'TMPL', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text


def _unquote_yaml_scalar(value: str) -> str:
    """Best-effort unquote for scalar strings found by the fallback parser."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return value.replace("''", "'")


def _extract_exprs_from_text(text: str) -> list[str]:
    """Fallback extraction for dashboards that are not valid YAML."""
    lines = text.splitlines()
    expressions = []
    expr_re = re.compile(r'^(?P<indent>\s*)expr:\s*(?P<value>.*)$')

    for idx, line in enumerate(lines):
        match = expr_re.match(line)
        if not match:
            continue

        raw_value = match.group('value').strip()
        if not raw_value:
            continue

        if raw_value in {'|', '|-', '|+', '>', '>-', '>+'}:
            base_indent = len(match.group('indent'))
            block_indent = None
            block_lines = []

            for next_line in lines[idx + 1:]:
                if not next_line.strip():
                    block_lines.append('')
                    continue

                indent = len(next_line) - len(next_line.lstrip(' '))
                if indent <= base_indent:
                    break

                if block_indent is None:
                    block_indent = indent
                block_lines.append(next_line[block_indent:])

            expr = ' '.join(part.strip() for part in block_lines if part.strip())
        else:
            expr = _unquote_yaml_scalar(raw_value)

        expr = re.sub(r'\s+', ' ', expr.strip())
        if expr and expr != 'TMPL':
            expressions.append(expr)

    return expressions


def parse_dashboard_file_fallback(filepath: Path, parse_error: Exception) -> dict[str, Any] | None:
    """Parse only dashboard expressions when the source is not valid YAML."""
    raw_text = filepath.read_text()
    text = strip_go_templates(raw_text)
    expressions = _extract_exprs_from_text(text)
    if not expressions:
        raise ValueError(f"failed to parse dashboard {filepath}: {parse_error}") from parse_error

    # Try to extract title via regex (top-level "title: ..." line)
    title = ''
    title_match = re.search(r'^title:\s*(.+)$', raw_text, re.MULTILINE)
    if title_match:
        title = title_match.group(1).strip().strip('"').strip("'")

    extracted_panels = []
    all_metrics = set()
    for expr in expressions:
        metrics = extract_metrics_from_expr(expr)
        all_metrics.update(metrics)
        extracted_panels.append({
            'title': '',
            'type': '',
            'queries': [{
                'expr': expr,
                'datasource_type': '',
                'metrics': metrics,
            }],
        })

    return {
        'name': filepath.stem,
        'title': title,
        'category': filepath.parent.name,
        'file': str(filepath.relative_to(REPO_ROOT)),
        'panel_count': len(extracted_panels),
        'referenced_metrics': sorted(all_metrics),
        'panels': extracted_panels,
        'parse_mode': 'regex_fallback',
        'parse_error': str(parse_error).split('\n', 1)[0],
    }


def parse_dashboard_file(filepath: Path) -> dict[str, Any] | None:
    """Parse a dashboard YAML file and extract panel info."""
    text = filepath.read_text()
    cleaned = strip_go_templates(text)
    try:
        data = yaml.safe_load(cleaned)
    except yaml.YAMLError as e:
        return parse_dashboard_file_fallback(filepath, e)

    if not data or not isinstance(data, dict):
        return None

    panels = data.get('panels', [])
    if not panels:
        return None

    category = filepath.parent.name
    dashboard_name = filepath.stem

    extracted_panels = []
    for panel in panels:
        if not isinstance(panel, dict):
            continue
        panel_info = _extract_panel(panel)
        if panel_info:
            extracted_panels.append(panel_info)
        for sub in panel.get('panels', []):
            if isinstance(sub, dict):
                sub_info = _extract_panel(sub)
                if sub_info:
                    extracted_panels.append(sub_info)

    if not extracted_panels:
        return None

    all_metrics = set()
    for p in extracted_panels:
        for q in p.get('queries', []):
            all_metrics.update(q.get('metrics', []))

    return {
        'name': dashboard_name,
        'title': data.get('title', ''),
        'category': category,
        'file': str(filepath.relative_to(REPO_ROOT)),
        'panel_count': len(extracted_panels),
        'referenced_metrics': sorted(all_metrics),
        'panels': extracted_panels,
        'parse_mode': 'yaml',
    }


def _extract_panel(panel: dict) -> dict[str, Any] | None:
    """Extract query info from a single panel."""
    title = panel.get('title', '')
    panel_type = panel.get('type', '')
    targets = panel.get('targets', [])
    if not targets:
        return None

    queries = []
    for target in targets:
        if not isinstance(target, dict):
            continue
        expr = target.get('expr', '')
        if not expr or expr == 'TMPL':
            continue
        expr = re.sub(r'\s+', ' ', expr.strip())
        ds = target.get('datasource', {})
        ds_type = ds.get('type', '') if isinstance(ds, dict) else ''
        metrics = extract_metrics_from_expr(expr)
        queries.append({
            'expr': expr,
            'datasource_type': ds_type,
            'metrics': metrics,
        })

    if not queries:
        return None

    return {'title': title, 'type': panel_type, 'queries': queries}


def generate_dashboards(docs: list[dict]) -> tuple[dict[str, Any], dict[str, Any], set[str]]:
    """Generate dashboards.yaml (slim) and dashboard_queries.full.yaml (detailed).

    Returns (slim_data, full_data, all_metrics) tuple.
    """
    parsed = []
    all_metrics = set()

    # Parse dashboard source files for panel/query info
    if DASHBOARDS_DIR.exists():
        for yaml_file in sorted(DASHBOARDS_DIR.rglob('*.yaml')):
            result = parse_dashboard_file(yaml_file)
            if result:
                parsed.append(result)
                all_metrics.update(result['referenced_metrics'])

    # Cross-reference with rendered GrafanaDashboard resources
    rendered_names = set()
    for doc in get_resources_by_kind(docs, "GrafanaDashboard"):
        meta = doc.get("metadata", {})
        rendered_names.add(meta.get("name", ""))

    source_names = {d['name'] for d in parsed}

    # Classify dashboards
    source_only = sorted(source_names - rendered_names)
    rendered_only = sorted(rendered_names - source_names)
    matched = sorted(source_names & rendered_names)

    # Build slim dashboard entries
    slim_dashboards = []
    for d in parsed:
        slim_dashboards.append({
            'name': d['name'],
            'title': d.get('title') or d['name'],
            'category': d['category'],
            'file': d['file'],
            'rendered': d['name'] in rendered_names,
        })

    slim_data = {
        'total_dashboards': len(parsed),
        'total_rendered_grafanadashboard_resources': len(rendered_names),
        'source_only': source_only,
        'rendered_only': rendered_only,
        'matched': matched,
        'dashboards': slim_dashboards,
    }

    # Build full query detail file
    full_entries = []
    for d in parsed:
        for p in d['panels']:
            for q in p.get('queries', []):
                full_entries.append({
                    'dashboard': d['name'],
                    'category': d['category'],
                    'panel_title': p['title'],
                    'panel_type': p['type'],
                    'expr': q['expr'],
                    'datasource_type': q.get('datasource_type', ''),
                    'metrics': q.get('metrics', []),
                })

    full_data = {
        'total_queries': len(full_entries),
        'queries': full_entries,
    }

    return slim_data, full_data, all_metrics


# ---------------------------------------------------------------------------
# Alerts & Recording Rules (from rendered PrometheusRule resources)
# ---------------------------------------------------------------------------


def generate_alerts_and_rules(docs: list[dict]) -> tuple[dict, dict]:
    """Generate alerts.yaml and recording_rules.yaml from rendered PrometheusRule."""
    prom_rules = get_resources_by_kind(docs, "PrometheusRule")

    all_alerts = []
    all_records = []
    alert_metrics = set()
    record_metrics = set()

    for pr in prom_rules:
        meta = pr.get("metadata", {})
        resource_name = meta.get("name", "")
        namespace = meta.get("namespace", "")
        source_chart = pr.get("_source_chart", "")

        spec = pr.get("spec", {})
        for group in spec.get("groups", []):
            group_name = group.get("name", "")
            for rule in group.get("rules", []):
                expr = rule.get("expr", "")
                if isinstance(expr, (int, float)):
                    expr = str(expr)
                # Strip PromQL comments (lines starting with #)
                expr_clean = '\n'.join(
                    l for l in expr.split('\n')
                    if not l.strip().startswith('#')
                )
                expr_clean = re.sub(r'\s+', ' ', expr_clean).strip()
                metrics = extract_metrics_from_expr(expr_clean)

                if "alert" in rule:
                    severity = rule.get("labels", {}).get("severity", "")
                    for_duration = rule.get("for", "")
                    all_alerts.append({
                        'name': rule["alert"],
                        'group': group_name,
                        'expr': expr_clean,
                        'for': for_duration,
                        'severity': severity,
                        'metrics': metrics,
                        'resource': resource_name,
                        'namespace': namespace,
                        'source_chart': source_chart,
                    })
                    alert_metrics.update(metrics)

                elif "record" in rule:
                    all_records.append({
                        'name': rule["record"],
                        'group': group_name,
                        'expr': expr_clean,
                        'metrics': metrics,
                        'resource': resource_name,
                        'namespace': namespace,
                        'source_chart': source_chart,
                    })
                    record_metrics.update(metrics)

    alerts_data = {
        'total_alerts': len(all_alerts),
        'total_groups': len(set(a['group'] for a in all_alerts)),
        'unique_referenced_metrics': sorted(alert_metrics),
        'alerts': all_alerts,
    }

    rules_data = {
        'total_recording_rules': len(all_records),
        'total_groups': len(set(r['group'] for r in all_records)),
        'unique_referenced_metrics': sorted(record_metrics),
        'recording_rules': all_records,
    }

    return alerts_data, rules_data


# ---------------------------------------------------------------------------
# Metrics (aggregated from all sources)
# ---------------------------------------------------------------------------


def generate_metrics(dashboard_metrics: set, alerts_data: dict,
                     rules_data: dict) -> dict[str, Any]:
    """Generate metrics.yaml with classification of all referenced metrics.

    Dashboard-referenced metrics are informational (required=false).
    Only critical_runtime_metrics are required=true.
    """
    alert_metrics = set(alerts_data.get('unique_referenced_metrics', []))
    record_metrics = set(rules_data.get('unique_referenced_metrics', []))
    critical_metrics = set(CRITICAL_RUNTIME_METRICS)

    all_metrics = dashboard_metrics | alert_metrics | record_metrics | critical_metrics

    # Classify each metric
    classified = []
    for m in sorted(all_metrics):
        entry = {
            'name': m,
            'sources': [],
            'required': m in critical_metrics,
        }
        if m in dashboard_metrics:
            entry['sources'].append('dashboard')
        if m in alert_metrics:
            entry['sources'].append('alert')
        if m in record_metrics:
            entry['sources'].append('recording_rule')
        if m in critical_metrics:
            entry['sources'].append('critical_runtime')
        classified.append(entry)

    # Required labels (common across KOF queries)
    required_labels = [
        {'name': 'cluster', 'description': 'Cluster name identifier'},
        {'name': 'namespace', 'description': 'Kubernetes namespace'},
        {'name': 'pod', 'description': 'Pod name'},
        {'name': 'container', 'description': 'Container name'},
        {'name': 'node', 'description': 'Node name'},
        {'name': 'job', 'description': 'Scrape job name'},
        {'name': 'service', 'description': 'Service name'},
        {'name': 'instance', 'description': 'Target instance'},
    ]

    return {
        'total_unique_metrics': len(all_metrics),
        'dashboard_referenced_count': len(dashboard_metrics),
        'alert_referenced_count': len(alert_metrics),
        'recording_rule_referenced_count': len(record_metrics),
        'critical_runtime_count': len(critical_metrics),
        'required_labels': required_labels,
        'critical_runtime_metrics': sorted(critical_metrics),
        'metrics': classified,
    }


# ---------------------------------------------------------------------------
# Datasources (from rendered GrafanaDatasource)
# ---------------------------------------------------------------------------


def generate_datasources(docs: list[dict]) -> dict[str, Any]:
    """Generate datasources.yaml from rendered GrafanaDatasource resources."""
    datasources = []

    for doc in get_resources_by_kind(docs, "GrafanaDatasource"):
        meta = doc.get("metadata", {})
        spec = doc.get("spec", {})
        ds_spec = spec.get("datasource", {})

        datasources.append({
            'name': ds_spec.get("name", meta.get("name", "")),
            'type': ds_spec.get("type", ""),
            'uid': ds_spec.get("uid", ""),
            'access': ds_spec.get("access", ""),
            'url': ds_spec.get("url", ""),
            'resource_name': meta.get("name", ""),
            'namespace': meta.get("namespace", ""),
            'is_default': ds_spec.get("isDefault", False),
        })

    # Also check for datasource references in chart templates (not rendered)
    # kof-storage has datasources too
    storage_ds_templates = list(
        (CHARTS_DIR / "kof-storage" / "templates" / "grafana").glob("*datasource*")
    ) if (CHARTS_DIR / "kof-storage" / "templates" / "grafana").exists() else []

    additional_sources = []
    for f in storage_ds_templates:
        text = f.read_text()
        # Extract name from template
        name_match = re.search(r'name:\s*(.+)', text[text.find('datasource:'):] if 'datasource:' in text else text)
        type_match = re.search(r'type:\s*(\w+)', text[text.find('datasource:'):] if 'datasource:' in text else text)
        if name_match:
            additional_sources.append({
                'name': re.sub(r'\{\{.*?\}\}', 'TMPL', name_match.group(1).strip()),
                'type': type_match.group(1).strip() if type_match else '',
                'source_template': str(f.relative_to(REPO_ROOT)),
                'note': 'From kof-storage chart (requires storage enabled)',
            })

    return {
        'total_datasources': len(datasources),
        'rendered_datasources': datasources,
        'additional_chart_datasources': additional_sources,
    }


# ---------------------------------------------------------------------------
# Collectors (from rendered OpenTelemetryCollector)
# ---------------------------------------------------------------------------


def generate_collectors(docs: list[dict]) -> dict[str, Any]:
    """Generate collectors.yaml from rendered OpenTelemetryCollector resources."""
    collectors = []

    for doc in get_resources_by_kind(docs, "OpenTelemetryCollector"):
        meta = doc.get("metadata", {})
        spec = doc.get("spec", {})

        # Parse OTel config from spec.config
        config_str = spec.get("config", "")
        otel_config = {}
        if isinstance(config_str, str) and config_str:
            try:
                otel_config = yaml.safe_load(config_str)
            except yaml.YAMLError:
                pass
        elif isinstance(config_str, dict):
            otel_config = config_str

        # Extract pipeline topology
        service = otel_config.get("service", {}) if isinstance(otel_config, dict) else {}
        pipelines = service.get("pipelines", {}) if isinstance(service, dict) else {}

        pipeline_info = {}
        for pipe_name, pipe_cfg in pipelines.items():
            if isinstance(pipe_cfg, dict):
                pipeline_info[pipe_name] = {
                    'receivers': pipe_cfg.get('receivers', []),
                    'processors': pipe_cfg.get('processors', []),
                    'exporters': pipe_cfg.get('exporters', []),
                }

        # Extract receiver/processor/exporter configs (names only)
        receivers = sorted(otel_config.get("receivers", {}).keys()) if isinstance(otel_config.get("receivers"), dict) else []
        processors = sorted(otel_config.get("processors", {}).keys()) if isinstance(otel_config.get("processors"), dict) else []
        exporters = sorted(otel_config.get("exporters", {}).keys()) if isinstance(otel_config.get("exporters"), dict) else []

        collectors.append({
            'name': meta.get("name", ""),
            'namespace': meta.get("namespace", ""),
            'mode': spec.get("mode", ""),
            'source_chart': doc.get("_source_chart", ""),
            'receivers': receivers,
            'processors': processors,
            'exporters': exporters,
            'pipelines': pipeline_info,
        })

    # Also parse Instrumentation resources
    instrumentations = []
    for doc in get_resources_by_kind(docs, "Instrumentation"):
        meta = doc.get("metadata", {})
        spec = doc.get("spec", {})
        instrumentations.append({
            'name': meta.get("name", ""),
            'namespace': meta.get("namespace", ""),
            'exporter_endpoint': spec.get("exporter", {}).get("endpoint", ""),
            'propagators': spec.get("propagators", []),
        })

    return {
        'total_collectors': len(collectors),
        'total_instrumentations': len(instrumentations),
        'collectors': collectors,
        'instrumentations': instrumentations,
    }


# ---------------------------------------------------------------------------
# Service Monitors (from rendered ServiceMonitor/PodMonitor)
# ---------------------------------------------------------------------------


def generate_service_monitors(docs: list[dict]) -> dict[str, Any]:
    """Generate service_monitors.yaml from rendered resources."""
    monitors = []

    for kind in ("ServiceMonitor", "PodMonitor"):
        for doc in get_resources_by_kind(docs, kind):
            meta = doc.get("metadata", {})
            spec = doc.get("spec", {})

            # Extract endpoints
            endpoints_key = "endpoints" if kind == "ServiceMonitor" else "podMetricsEndpoints"
            endpoints = spec.get(endpoints_key, [])

            endpoint_info = []
            for ep in endpoints:
                if isinstance(ep, dict):
                    endpoint_info.append({
                        'port': ep.get('port', ''),
                        'path': ep.get('path', '/metrics'),
                        'interval': ep.get('interval', ''),
                        'scheme': ep.get('scheme', ''),
                    })

            # Extract selector
            selector = spec.get("selector", {})
            match_labels = selector.get("matchLabels", {})

            # Namespace selector
            ns_selector = spec.get("namespaceSelector", {})

            monitors.append({
                'kind': kind,
                'name': meta.get("name", ""),
                'namespace': meta.get("namespace", ""),
                'source_chart': doc.get("_source_chart", ""),
                'selector_labels': match_labels,
                'namespace_selector': ns_selector,
                'endpoints': endpoint_info,
            })

    return {
        'total_monitors': len(monitors),
        'service_monitors': [m for m in monitors if m['kind'] == 'ServiceMonitor'],
        'pod_monitors': [m for m in monitors if m['kind'] == 'PodMonitor'],
    }


# ---------------------------------------------------------------------------
# Logs (from OTel collector log pipelines)
# ---------------------------------------------------------------------------


def generate_logs(collectors_data: dict) -> dict[str, Any]:
    """Generate logs.yaml from collector log pipelines."""
    log_pipelines = []

    for coll in collectors_data.get('collectors', []):
        for pipe_name, pipe_cfg in coll.get('pipelines', {}).items():
            if 'logs' in pipe_name:
                log_pipelines.append({
                    'collector': coll['name'],
                    'collector_mode': coll['mode'],
                    'pipeline': pipe_name,
                    'receivers': pipe_cfg.get('receivers', []),
                    'processors': pipe_cfg.get('processors', []),
                    'exporters': pipe_cfg.get('exporters', []),
                })

    # Identify log sources and destinations
    log_receivers = set()
    log_exporters = set()
    for p in log_pipelines:
        log_receivers.update(p.get('receivers', []))
        log_exporters.update(p.get('exporters', []))

    return {
        'total_log_pipelines': len(log_pipelines),
        'log_receivers': sorted(log_receivers),
        'log_exporters': sorted(log_exporters),
        'pipelines': log_pipelines,
        'expected_sources': [
            {'type': 'k8s_events', 'description': 'Kubernetes events via k8sobjects receiver'},
            {'type': 'container_logs', 'description': 'Container stdout/stderr via filelog receiver'},
            {'type': 'otlp', 'description': 'Application logs via OTLP receiver'},
        ],
        'expected_destinations': [
            {'type': 'victoria_logs', 'description': 'VictoriaLogs cluster for log storage'},
        ],
    }


# ---------------------------------------------------------------------------
# Traces (from OTel collector trace pipelines)
# ---------------------------------------------------------------------------


def generate_traces(collectors_data: dict) -> dict[str, Any]:
    """Generate traces.yaml from collector trace pipelines."""
    trace_pipelines = []

    for coll in collectors_data.get('collectors', []):
        for pipe_name, pipe_cfg in coll.get('pipelines', {}).items():
            if 'traces' in pipe_name:
                trace_pipelines.append({
                    'collector': coll['name'],
                    'collector_mode': coll['mode'],
                    'pipeline': pipe_name,
                    'receivers': pipe_cfg.get('receivers', []),
                    'processors': pipe_cfg.get('processors', []),
                    'exporters': pipe_cfg.get('exporters', []),
                })

    trace_receivers = set()
    trace_exporters = set()
    for p in trace_pipelines:
        trace_receivers.update(p.get('receivers', []))
        trace_exporters.update(p.get('exporters', []))

    return {
        'total_trace_pipelines': len(trace_pipelines),
        'trace_receivers': sorted(trace_receivers),
        'trace_exporters': sorted(trace_exporters),
        'pipelines': trace_pipelines,
        'expected_sources': [
            {'type': 'otlp', 'description': 'Application traces via OTLP receiver'},
            {'type': 'auto_instrumentation', 'description': 'Auto-instrumented traces via Instrumentation CR'},
        ],
        'expected_destinations': [
            {'type': 'victoria_traces', 'description': 'VictoriaTraces cluster for trace storage'},
        ],
    }


# ---------------------------------------------------------------------------
# Kubernetes Resources Inventory
# ---------------------------------------------------------------------------


def generate_kubernetes_resources(docs: list[dict]) -> dict[str, Any]:
    """Generate kubernetes_resources.yaml — expected resource inventory."""
    resources_by_key = {}

    for doc in docs:
        kind = doc.get("kind", "")
        if not kind:
            continue

        meta = doc.get("metadata", {})
        source_chart = doc.get("_source_chart", "")
        key = (kind, meta.get("namespace", ""), meta.get("name", ""))
        if key not in resources_by_key:
            resources_by_key[key] = {
                'kind': kind,
                'name': meta.get("name", ""),
                'namespace': meta.get("namespace", ""),
                'source_chart': source_chart,
                'source_charts': [source_chart] if source_chart else [],
            }
            continue

        source_charts = resources_by_key[key]['source_charts']
        if source_chart and source_chart not in source_charts:
            source_charts.append(source_chart)

    resources = sorted(
        resources_by_key.values(),
        key=lambda r: (r['kind'], r['namespace'], r['name']),
    )

    # Group by kind for summary
    by_kind = {}
    for r in resources:
        by_kind.setdefault(r['kind'], []).append(r)

    # Filter to observability-relevant kinds for detailed listing
    observability_resources = [r for r in resources if r['kind'] in OBSERVABILITY_KINDS]

    # Also scan for resources not rendered (from kof-storage templates)
    unrendered_resources = _scan_unrendered_templates()

    return {
        'total_resources': len(resources),
        'total_observability_resources': len(observability_resources),
        'by_kind_summary': {k: len(v) for k, v in sorted(by_kind.items())},
        'observability_resources': observability_resources,
        'unrendered_resources_note': (
            'Some resources require runtime context (Lookup, Secrets) '
            'and cannot be rendered with helm template. Listed below from source templates.'
        ),
        'unrendered_resources': unrendered_resources,
    }


def _scan_unrendered_templates() -> list[dict]:
    """Scan chart templates for resources that helm template cannot render."""
    unrendered = []

    # kof-storage templates
    storage_templates = CHARTS_DIR / "kof-storage" / "templates"
    if storage_templates.exists():
        for f in sorted(storage_templates.rglob("*.yaml")):
            text = f.read_text()
            for kind in OBSERVABILITY_KINDS:
                if f"kind: {kind}" in text:
                    name_match = re.search(r'name:\s*(.+)', text[text.find(f'kind: {kind}'):])
                    name = name_match.group(1).strip() if name_match else f.stem
                    name = re.sub(r'\{\{.*?\}\}', 'TMPL', name).strip('"').strip("'")
                    unrendered.append({
                        'kind': kind,
                        'name': name,
                        'source_template': str(f.relative_to(REPO_ROOT)),
                        'chart': 'kof-storage',
                    })

    return unrendered


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def write_yaml(data: Any, path: Path) -> None:
    """Write data as YAML with header comment."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        f.write(YAML_HEADER)
        yaml.dump(data, f, default_flow_style=False, sort_keys=False,
                  width=120, allow_unicode=True)
    print(f"  wrote: {path.relative_to(REPO_ROOT)}")


def generate_index(all_data: dict[str, dict]) -> dict[str, Any]:
    """Generate index.yaml summarizing all reference files."""
    return {
        'description': (
            'KOF Observability Reference Dataset — static inventory of expected '
            'Kubernetes resources, metrics, alerts, dashboards, and pipelines '
            'after a KOF installation.'
        ),
        'generated_by': 'scripts/generate_reference.py',
        'regenerate_command': 'make generate-reference',
        'check_command': 'make check-reference',
        'files': {
            'dashboards.yaml': {
                'description': 'Dashboard inventory (slim: name, category, counts, datasource types)',
                'count': all_data['dashboards']['total_dashboards'],
            },
            'dashboard_queries.full.yaml': {
                'description': 'Full panel/query detail (optional, not for PR review)',
                'count': all_data['dashboards']['total_dashboards'],
                'note': 'Large file — detailed query expressions for debugging',
            },
            'metrics.yaml': {
                'description': 'All referenced metrics with source classification',
                'count': all_data['metrics']['total_unique_metrics'],
            },
            'alerts.yaml': {
                'description': 'PrometheusRule alert definitions',
                'count': all_data['alerts']['total_alerts'],
            },
            'recording_rules.yaml': {
                'description': 'PrometheusRule recording rule definitions',
                'count': all_data['recording_rules']['total_recording_rules'],
            },
            'datasources.yaml': {
                'description': 'GrafanaDatasource resources',
                'count': all_data['datasources']['total_datasources'],
            },
            'collectors.yaml': {
                'description': 'OpenTelemetryCollector pipeline configurations',
                'count': all_data['collectors']['total_collectors'],
            },
            'service_monitors.yaml': {
                'description': 'ServiceMonitor and PodMonitor definitions',
                'count': all_data['service_monitors']['total_monitors'],
            },
            'logs.yaml': {
                'description': 'Log pipeline topology and expected sources',
                'count': all_data['logs']['total_log_pipelines'],
            },
            'traces.yaml': {
                'description': 'Trace pipeline topology and expected sources',
                'count': all_data['traces']['total_trace_pipelines'],
            },
            'kubernetes_resources.yaml': {
                'description': 'Complete K8s resource inventory from rendered charts',
                'count': all_data['kubernetes_resources']['total_resources'],
            },
        },
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    print("KOF Observability Reference Dataset Generator")
    print("=" * 55)
    print("Generating static reference dataset from Helm charts...\n")

    # Ensure output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Step 1: Render Helm charts
    print("[1/8] Rendering Helm charts...")
    docs = render_all_charts()
    print(f"  total rendered resources: {len(docs)}\n")

    # Step 2: Dashboards (slim + full queries)
    print("[2/8] Parsing dashboards...")
    dashboards_data, queries_full_data, dashboard_metrics = generate_dashboards(docs)
    write_yaml(dashboards_data, OUTPUT_DIR / "dashboards.yaml")
    write_yaml(queries_full_data, OUTPUT_DIR / "dashboard_queries.full.yaml")

    # Step 3: Alerts and Recording Rules
    print("[3/8] Extracting alerts and recording rules...")
    alerts_data, rules_data = generate_alerts_and_rules(docs)
    write_yaml(alerts_data, OUTPUT_DIR / "alerts.yaml")
    write_yaml(rules_data, OUTPUT_DIR / "recording_rules.yaml")

    # Step 4: Metrics (aggregated)
    print("[4/8] Aggregating metrics...")
    metrics_data = generate_metrics(dashboard_metrics, alerts_data, rules_data)
    write_yaml(metrics_data, OUTPUT_DIR / "metrics.yaml")

    # Step 5: Datasources
    print("[5/8] Extracting datasources...")
    datasources_data = generate_datasources(docs)
    write_yaml(datasources_data, OUTPUT_DIR / "datasources.yaml")

    # Step 6: Collectors
    print("[6/8] Extracting collector configurations...")
    collectors_data = generate_collectors(docs)
    write_yaml(collectors_data, OUTPUT_DIR / "collectors.yaml")

    # Step 7: Service Monitors
    print("[7/8] Extracting service monitors...")
    svc_monitors_data = generate_service_monitors(docs)
    write_yaml(svc_monitors_data, OUTPUT_DIR / "service_monitors.yaml")

    # Step 8: Logs, Traces, K8s Resources
    print("[8/8] Generating logs, traces, and resource inventory...")
    logs_data = generate_logs(collectors_data)
    write_yaml(logs_data, OUTPUT_DIR / "logs.yaml")

    traces_data = generate_traces(collectors_data)
    write_yaml(traces_data, OUTPUT_DIR / "traces.yaml")

    k8s_data = generate_kubernetes_resources(docs)
    write_yaml(k8s_data, OUTPUT_DIR / "kubernetes_resources.yaml")

    # Index
    all_data = {
        'dashboards': dashboards_data,
        'metrics': metrics_data,
        'alerts': alerts_data,
        'recording_rules': rules_data,
        'datasources': datasources_data,
        'collectors': collectors_data,
        'service_monitors': svc_monitors_data,
        'logs': logs_data,
        'traces': traces_data,
        'kubernetes_resources': k8s_data,
    }
    index_data = generate_index(all_data)
    write_yaml(index_data, OUTPUT_DIR / "index.yaml")

    # Summary
    print("\n" + "=" * 55)
    print("Reference Dataset Summary:")
    print(f"  Dashboards:       {dashboards_data['total_dashboards']}")
    print(f"  Queries (full):   {queries_full_data['total_queries']}")
    print(f"  Metrics:          {metrics_data['total_unique_metrics']} unique")
    print(f"  Alerts:           {alerts_data['total_alerts']}")
    print(f"  Recording Rules:  {rules_data['total_recording_rules']}")
    print(f"  Datasources:      {datasources_data['total_datasources']}")
    print(f"  Collectors:       {collectors_data['total_collectors']}")
    print(f"  Service Monitors: {svc_monitors_data['total_monitors']}")
    print(f"  Log Pipelines:    {logs_data['total_log_pipelines']}")
    print(f"  Trace Pipelines:  {traces_data['total_trace_pipelines']}")
    print(f"  K8s Resources:    {k8s_data['total_resources']}")
    print(f"\nOutput: {OUTPUT_DIR.relative_to(REPO_ROOT)}/")


if __name__ == '__main__':
    main()
