{{- if .Values.grafana.security.create_secret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.grafana.security.credentials_secret_name) }}
{{- $username := randAlpha (.Values.global.random_username_length | int) }}
{{- $password := randAlpha (.Values.global.random_password_length | int) }}
{{- if $secret }}
{{- $username = index $secret.data "GF_SECURITY_ADMIN_USER" | b64dec }}
{{- $password = index $secret.data "GF_SECURITY_ADMIN_PASSWORD" | b64dec }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.grafana.security.credentials_secret_name }}
  namespace: {{ .Release.Namespace }}
stringData:
  GF_SECURITY_ADMIN_USER: {{ $username | quote }} # Grafana username
  GF_SECURITY_ADMIN_PASSWORD: {{ $password | quote }} # Grafana password
type: Opaque
{{- end }}
