global:
  clusterLabel: clusterName
  storageClass: ""
  clusterName: mothership
kcm:
  installTemplates: true
victoriametrics:
  enabled: enabled
  vmcluster:
    enabled: true
    replicationFactor: 1
    replicaCount: 1
  vmalert:
    enabled: true
    remoteRead: ""
grafana:
  enabled: true
  ingress:
    enabled: false
    host: grafana.example.net
  alerts:
    enabled: true
  logSources:
    - name: storage0-logs
      url: https://vmauth.kcm0.example.net/vls
      type: victorialogs-datasource
      auth:
        credentials_secret_name: storage-vmuser-credentials
        username_key: "username"
        password_key: "password"
  security:
    credentials_secret_name: grafana-admin-credentials
victoria-metrics-operator:
  enabled: true
  crds:
    plain: true
promxy:
  replicaCount: 1
  deployment:
    enabled: true
  image:
    repository: quay.io/jacksontj/promxy
    tag: "latest"
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    annotations: {}
    # If not set, generated using the fullname template
    name:
  service:
    type: ClusterIP
    enabled: true
    servicePort: 8082
    annotations: {}
    extraLabels: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    extraLabels: {}
    path: /
    pathType: Prefix
    hosts:
      - example.com
    tls: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  extraArgs:
    log-level: "info"
