{{- if .Values.rootCA.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kof-namespace-template
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  namespace.yaml: |
    kind: Namespace
    apiVersion: v1
    metadata:
      name: kof
      labels:
        istio-injection: enabled
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ .Release.Name }}-kof-namespace
spec:
  tier: 50
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: child
  policyRefs:
  - name: {{ .Release.Name }}-kof-namespace-template
    namespace: {{ $.Release.Namespace }}
    kind: ConfigMap
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: kof-istio-child-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: child
  serviceSpec:
    priority: 100
    services:

      - name: cert-manager
        namespace: istio-system
        template: cert-manager-1-16-2
        values: |
          cert-manager:
            crds:
              enabled: true

      - name: kof-istio
        namespace: istio-system
        template: kof-istio-0-1-1
        values: |
          rootCA:
            enabled: false
          intermediateCAs:
            {{ `{{ .Cluster.metadata.name }}` }}:
              certificate: false
              issuer: true
            mothership:
              certificate: false
              issuer: false
          global:
            multiCluster:
              clusterName: {{ `{{ .Cluster.metadata.name }}` }}
            network: {{ `{{ .Cluster.metadata.name }}` }}-network
          cert-manager-istio-csr:
            app:
              certmanager:
                issuer:
                  name: {{ $.Release.Name }}-{{ `{{ .Cluster.metadata.name }}` }}-ca
              server:
                clusterID: {{ `{{ .Cluster.metadata.name }}` }}
          gateway:
            enabled: {{ `{{ eq (get .Cluster.metadata.labels "k0rdent.mirantis.com/kof-cluster-role") "regional" }}` }}
            networkGateway: {{ `{{ .Cluster.metadata.name }}` }}-network
{{- end }}
