{{- if .Values.rootCA.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kof-namespace-template
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  namespace.yaml: |
    kind: Namespace
    apiVersion: v1
    metadata:
      name: {{ .Values.kof.namespace }}
      labels:
        istio-injection: enabled
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ .Release.Name }}-kof-namespace
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: child
  policyRefs:
  - name: {{ .Release.Name }}-kof-namespace-template
    namespace: {{ $.Release.Namespace }}
    kind: ConfigMap
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ .Release.Name }}-network
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: child
  helmCharts:

    - repositoryName:   k0rdent-catalog
      repositoryURL:    oci://ghcr.io/k0rdent/catalog/charts
      chartName:        cert-manager
      chartVersion:     1.16.2
      releaseName:      cert-manager
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install
      values: |
        cert-manager:
          crds:
            enabled: true

    - repositoryName:   {{ .Values.kcm.kof.repo.name }}
      repositoryURL:    {{ .Values.kcm.kof.repo.url }}
      {{- if eq .Values.kcm.kof.repo.type "oci" }}
      chartName:        kof-istio
      {{- else }}
      chartName:        {{ .Values.kcm.kof.repo.name }}/kof-istio
      {{- end }}
      chartVersion:     {{ .Chart.Version }}
      releaseName:      kof-istio
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install
      options:
        wait: true
        timeout: "10m"
      values: |
        rootCA:
          enabled: false
        intermediateCAs:
          {{ `{{ .Cluster.metadata.name }}` }}:
            certificate: false
            issuer: true
          mothership:
            certificate: false
            issuer: false
        global:
          multiCluster:
            clusterName: {{ `{{ .Cluster.metadata.name }}` }}
          network: {{ `{{ .Cluster.metadata.name }}` }}-network
        cert-manager-istio-csr:
          app:
            certmanager:
              issuer:
                name: {{ $.Release.Name }}-{{ `{{ .Cluster.metadata.name }}` }}-ca
            server:
              clusterID: {{ `{{ .Cluster.metadata.name }}` }}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ .Release.Name }}-storage
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: child
      k0rdent.mirantis.com/kof-cluster-role: regional
  dependsOn:
    - {{ .Release.Name }}-kof-namespace
    - {{ .Release.Name }}-network
  helmCharts:
    - repositoryName:   istio
      repositoryURL:    https://istio-release.storage.googleapis.com/charts
      chartName:        istio/gateway
      chartVersion:     1.24.3
      releaseName:      {{ .Release.Name }}-gateway
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install
      values: |
        global:
          multiCluster:
            clusterName: {{ `{{ .Cluster.metadata.name }}` }}
          network: {{ `{{ .Cluster.metadata.name }}` }}-network
        networkGateway: {{ `{{ .Cluster.metadata.name }}` }}-network

    - repositoryName:   {{ .Values.kcm.kof.repo.name }}
      repositoryURL:    {{ .Values.kcm.kof.repo.url }}
      {{- if eq .Values.kcm.kof.repo.type "oci" }}
      chartName:        kof-storage
      {{- else }}
      chartName:        {{ .Values.kcm.kof.repo.name }}/kof-storage
      {{- end }}
      chartVersion:     {{ .Chart.Version }}
      releaseName:      kof-storage
      releaseNamespace: {{ .Values.kof.namespace }}
      helmChartAction:  Install
      values: |
        global:
          clusterName: {{ `{{ .Cluster.metadata.name }}` }}
        istio_endpoints: true
        jaeger:
          ingress:
            enabled: false
        victoriametrics:
          vmauth:
            enabled: false
        grafana:
          ingress:
            enabled: false

{{- end }}
