{{- if .Values.rootCA.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-secret-template
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  secret.yaml: |
    {{` {{ copy "Secret" }} `}}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: istio-child-ca-secret
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: child
  templateResourceRefs:
    - identifier: Secret
      resource:
        apiVersion: v1
        kind: Secret
        name: {{ $.Release.Name }}-{{ `{{ .Cluster.metadata.name }}` }}-ca
        namespace: {{ $.Release.Namespace }}
  policyRefs:
    - kind: ConfigMap
      name: {{ $.Release.Name }}-secret-template
      namespace: {{ $.Release.Namespace }}
{{- end }}
