{{- if .Values.rootCA.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-secret-template
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  secret.yaml: |
    {{` {{ copy "Secret" }} `}}
{{- end }}
