name: Patch kind config
description: Patch kind config to add registry mirror with authentication.
inputs:
  kind_config_path:
    description: 'Path to the kind config file'
    required: false
    default: $PWD/config/kind.yaml
  registry-username:
    description: Username for registry
    required: true
  registry-password:
    description: Password for registry
    required: true

runs:
  using: composite
  steps:
    - name: Patch kind config for registry mirror
      shell: bash
      run: |
        KIND_CONFIG_PATH="${{ inputs.kind_config_path }}"
        cat <<EOF > patches.yaml
        containerdConfigPatches:
          - |
            [plugins."io.containerd.grpc.v1.cri".registry]
              [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
                [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
                  endpoint = ["https://registry.ci.mirantis.com/dockerhub/"]
              [plugins."io.containerd.grpc.v1.cri".registry.configs]
                [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.ci.mirantis.com".auth]
                  username = "${{ inputs.registry-username }}"
                  password = "${{ inputs.registry-password }}"
        EOF
        sed -i '/apiVersion: kind.x-k8s.io\/v1alpha4/r patches.yaml' ${KIND_CONFIG_PATH}
        rm patches.yaml
