{{- $global := .Values.global | default dict }}
{{- $globalGlobal := dict "global" $global }}
{{- $customRegistry := $global.registry | default "" }}

{{- $istio := .Values.istio.enabled }}
{{- if $istio }}
  {{- $ns := lookup "v1" "Namespace" "" ($global.namespace | default "kof") }}
  {{- if $ns | dig "metadata" "labels" "istio-injection" "" | ne "enabled" }}
    {{- $istio = false }}
  {{- end }}
{{- end }}

{{- $m2m := .Values.fromManagement.toManagementCluster.enabled }}
{{- $m2r := .Values.fromManagement.toRegionalCluster.name | any }}
{{- if and $m2m $m2r }}
  {{- fail "`fromManagement.toManagementCluster` and `fromManagement.toRegionalCluster` cannot be enabled at the same time" }}
{{- end }}

{{- range $mgmt := (or $m2m $m2r) | ternary (list true false) (list false) }}
{{- if not $mgmt }}{{ $m2m = false }}{{ $m2r = false }}{{ end }}

---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: kof-{{ if $istio }}istio-{{ end }}{{ if $mgmt }}mgmt{{ else }}child{{ end }}-cluster
spec:
  clusterSelector:
    matchLabels:
    {{- if $mgmt }}
      k0rdent.mirantis.com/management-cluster: "true"
      # Workaround for https://github.com/k0rdent/kcm/issues/2610
    {{- else }}
      k0rdent.mirantis.com/kof-cluster-role: child
      {{- if $istio }}
      k0rdent.mirantis.com/istio-role: member
      {{- else }}
    matchExpressions:
      - key: "k0rdent.mirantis.com/istio-role"
        operator: DoesNotExist
      {{- end }}
    {{- end }}

  {{- if $istio }}
   {{- if $.Values.istio.dependsOn }}
  dependsOn:
  {{- range $.Values.istio.dependsOn }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- end }}

  serviceSpec:
    {{- if $mgmt }}
    provider:
      selfManagement: true
    {{- end }}

    services:
      {{- $version := $.Chart.Version | replace "." "-" }}

      {{- $installCertManager := and (index $.Values "cert-manager" "enabled") (not $istio) (not $mgmt) }}
      {{- if $installCertManager }}
      - name: cert-manager
        namespace: {{ $.Release.Namespace }}
        template: {{ index $.Values "cert-manager" "template" }}
        helmOptions:
          wait: true
        values: |
          crds:
            enabled: true
        {{- with $customRegistry }}
          image:
            repository: {{ . }}/jetstack/cert-manager-controller
          acmesolver:
            image:
              repository: {{ . }}/jetstack/cert-manager-acmesolver
          cainjector:
            image:
              repository: {{ . }}/jetstack/cert-manager-cainjector
          startupapicheck:
            image:
              repository: {{ . }}/jetstack/cert-manager-startupapicheck
          webhook:
            image:
              repository: {{ . }}/jetstack/cert-manager-webhook
        {{- end }}
      {{- end }}

      {{- if not $mgmt }}
      - name: kof-operators
        namespace: {{ $.Release.Namespace }}
        template: kof-operators-{{ $version }}
        templateChain: kof-operators-{{ $version }}
        helmOptions:
          wait: true
        {{- if $installCertManager }}
        dependsOn:
          - name: cert-manager
            namespace: {{ $.Release.Namespace }}
        {{- end }}
        values: |
          {{`{{`}} $operatorsValuesFromAnnotation := .Cluster.metadata | dig "annotations" "k0rdent.mirantis.com/kof-operators-values" "{}" | fromYaml {{`}}`}}
          {{`{{`}} $operatorsValuesFromHelm := `{{ $.Values.operators | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $globalValuesFromHelm := `{{ $globalGlobal | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} mergeOverwrite (dict) $globalValuesFromHelm $operatorsValuesFromHelm $operatorsValuesFromAnnotation | toYaml | nindent 4 {{`}}`}}
      {{- end }}

      {{- if $m2m }}
      - name: kof-storage
        namespace: {{ $.Release.Namespace }}
        template: kof-storage-{{ $version }}
        templateChain: kof-storage-{{ $version }}
        helmOptions:
          wait: true
        values: |
          {{`{{`}} $mgmtStorageValuesFromHelm := `{{ $.Values.fromManagement.storage | toYaml | nindent 10 }}` | fromYaml {{`}}`}}

          {{`{{`}} $storageValuesHere := `
          promxy:
            enabled: true  # Adds PromxyServerGroup only.
          victoria-traces-multilevel-select:
            enabled: true # Adds VMStorageConnection for traces.
          victoria-logs-multilevel-select:
            enabled: true # Adds VMStorageConnection for logs.
          victoriametrics:
            enabled: false  # It is enabled in kof-mothership.
          ` | fromYaml {{`}}`}}

          {{`{{`}} $globalValuesFromHelm := `{{ $globalGlobal | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} mergeOverwrite (dict) $globalValuesFromHelm $storageValuesHere $mgmtStorageValuesFromHelm | toYaml | nindent 4 {{`}}`}}
      {{- end }}

      - name: kof-collectors
        namespace: {{ $.Release.Namespace }}
        template: kof-collectors-{{ $version }}
        templateChain: kof-collectors-{{ $version }}
        helmOptions:
          wait: true
        {{- if $m2m }}
        dependsOn:
          - name: kof-storage
            namespace: {{ $.Release.Namespace }}
        {{- else if not $mgmt }}
        dependsOn:
          - name: kof-operators
            namespace: {{ $.Release.Namespace }}
        {{- end }}
        values: |
        {{- if $m2m }}
          {{`{{`}} $vmuserSecretName := "" {{`}}`}}
          {{`{{`}} $vmuserSecretVersion := "" {{`}}`}}
        {{- else }}
          {{/* `getField "StorageVMUserCredentials" "metadata.name"` leads to `secretKeyRef/name: got null, want string` in KCM Region case only */}}
          {{- if $m2r }}
          {{`{{`}} $vmuserSecretName := print "kof-vmuser-creds-admin-" (printf "kof-%s/%s" "{{ $.Values.fromManagement.toRegionalCluster.name }}" "{{ $.Values.fromManagement.toRegionalCluster.namespace }}" | adler32sum) {{`}}`}}
          {{- else }}
          {{`{{`}} $vmuserSecretName := print "kof-vmuser-creds-" (printf "kof-cluster-config-%s/%s" .Cluster.metadata.name .Cluster.metadata.namespace | adler32sum) {{`}}`}}
          {{- end }}
          {{`{{`}} $vmuserSecretVersion := getField "StorageVMUserCredentials" "metadata.resourceVersion" {{`}}`}}
        {{- end }}

        {{- if $m2r }}
          {{`{{`}} $regionalDomain := getResource "RegionalKCMCluster" | dig "metadata" "annotations" "k0rdent.mirantis.com/kof-regional-domain" "" {{`}}`}}
          {{`{{`}} if not $regionalDomain {{`}}`}}
            {{`{{`}} $regionalDomain = getResource "RegionalSveltosCluster" | dig "metadata" "annotations" "k0rdent.mirantis.com/kof-regional-domain" "" {{`}}`}}
          {{`{{`}} end {{`}}`}}
        {{- end }}

        {{- if $mgmt }}
          {{`{{`}} $childClusterName := "{{ $.Values.fromManagement.cluster.name }}" {{`}}`}}
          {{`{{`}} $childClusterNamespace := "{{ $.Values.fromManagement.cluster.namespace }}" {{`}}`}}
        {{- else }}
          {{`{{`}} $childClusterName := .Cluster.metadata.name {{`}}`}}
          {{`{{`}} $childClusterNamespace := .Cluster.metadata.namespace {{`}}`}}
        {{- end }}

        {{- if $istio }}
          {{- if $m2m }}
          {{`{{`}} $regionalClusterName := "" {{`}}`}}
          {{- else if $m2r }}
          {{`{{`}} $regionalClusterName := "{{ $.Values.fromManagement.toRegionalCluster.name }}" {{`}}`}}
          {{- else }}
          {{`{{`}} $regionalClusterName := getField "ChildConfig" "data.regional_cluster_name" {{`}}`}}
          {{- end }}
        {{- else if not $mgmt }}
          {{`{{`}} $writeMetricsEndpoint := getField "ChildConfig" "data.write_metrics_endpoint" {{`}}`}}
          {{`{{`}} $readMetricsEndpoint := getField "ChildConfig" "data.read_metrics_endpoint" {{`}}`}}
          {{`{{`}} $logsEndpoint := getField "ChildConfig" "data.write_logs_endpoint" {{`}}`}}
          {{`{{`}} $auditLogsEndpoint := getField "ChildConfig" "data.write_audit_logs_endpoint" {{`}}`}}
          {{`{{`}} $tracesEndpoint := getField "ChildConfig" "data.write_traces_endpoint" {{`}}`}}
        {{- end }}

          {{`{{`}} $collectorsValuesFromAnnotation := .Cluster.metadata | dig "annotations" "k0rdent.mirantis.com/kof-collectors-values" "{}" | fromYaml {{`}}`}}

        {{- if $mgmt }}
          {{`{{`}} $mgmtCollectorsValuesFromHelm := `{{ $.Values.fromManagement.collectors | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
        {{- else }}
          {{`{{`}} $mgmtCollectorsValuesFromHelm := dict {{`}}`}}
        {{- end }}

          {{`{{`}} $collectorsValuesFromHelm := `{{ $.Values.collectors | toYaml | nindent 10 }}` | fromYaml {{`}}`}}

          {{`{{`}} $collectorsValuesHere := `
          global:
            clusterName: {childClusterName}
            clusterNamespace: {childClusterNamespace}

          {{- if $mgmt }}
          kcm:
            monitoring: true
          {{- end }}

          opentelemetry-kube-stack:
            clusterName: {childClusterName}

            collectors:
            {{- if $istio }}
              controller-k0s:
                enabled: false
            {{- end }}
              daemon:
                image:
                  tag: v{{ $.Chart.AppVersion | trimPrefix "v" }}
              {{- if $istio }}
                hostNetwork: false
              {{- else }}
                hostNetwork: true
                observability:
                  metrics:
                    disablePrometheusAnnotations: false
                    enableMetrics: false
                podAnnotations:
                  prometheus.io/ip4: ${env:OTEL_K8S_NODE_IP}
              {{- end }}

              {{- if not $m2m }}
                config:
                {{- if not $istio }}
                  receivers:
                    prometheus:
                      api_server:
                        server_config:
                          endpoint: ${env:OTEL_K8S_NODE_IP}:9090
                    otlp:
                      protocols:
                        grpc:
                          endpoint: 0.0.0.0:4317
                        http:
                          endpoint: 0.0.0.0:4318
                {{- end }}

                  service:
                    extensions:
                      - k8s_observer
                      - file_storage/filelogreceiver
                      - file_storage/filelogsyslogreceiver
                      - file_storage/filelogk8sauditreceiver
                      - file_storage/journaldreceiver
                      - basicauth/metrics
                      - basicauth/logs
                      - basicauth/traces

                    {{- if not $istio }}
                    telemetry:
                      metrics:
                        readers:
                          - pull:
                              exporter:
                                prometheus:
                                  host: ${env:OTEL_K8S_NODE_IP}
                                  port: 8888
                    {{- end }}
              {{- end }}

            defaultCRConfig:
              podAnnotations:
                k0rdent.mirantis.com/kof-vmuser-secret-version: "{vmuserSecretVersion}"
              config:
                processors:
                  resource/k8sclustername:
                    attributes:
                    - action: insert
                      key: k8s.cluster.name
                      value: {childClusterName}
                    - action: insert
                      key: k8s.cluster.namespace
                      value: {childClusterNamespace}

              {{- if not $m2m }}
                extensions:
                  basicauth/logs:
                    client_auth:
                      username: ${env:KOF_VM_USER}
                      password: ${env:KOF_VM_PASSWORD}
                  basicauth/metrics:
                    client_auth:
                      username: ${env:KOF_VM_USER}
                      password: ${env:KOF_VM_PASSWORD}
                  basicauth/traces:
                    client_auth:
                      username: ${env:KOF_VM_USER}
                      password: ${env:KOF_VM_PASSWORD}
                service:
                  extensions:
                  - basicauth/logs
                  - basicauth/metrics
                  - basicauth/traces
              {{- end }}

                exporters:
                {{- if not $m2m }}
                  debug: {}
                  otlphttp/logs:
                  {{- if $istio }}
                    logs_endpoint: http://{regionalClusterName}-vmauth:8427/vli/insert/opentelemetry/v1/logs
                  {{- else if $m2r }}
                    logs_endpoint: https://vmauth.{regionalDomain}/vli/insert/opentelemetry/v1/logs
                  {{- else }}
                    logs_endpoint: {logsEndpoint}
                  {{- end }}
                    auth:
                      authenticator: basicauth/logs
                  otlphttp/logs-audit:
                  {{- if $istio }}
                    logs_endpoint: http://{regionalClusterName}-vmauth:8427/vlai/insert/opentelemetry/v1/logs
                  {{- else if $m2r }}
                    logs_endpoint: https://vmauth.{regionalDomain}/vlai/insert/opentelemetry/v1/logs
                  {{- else }}
                    logs_endpoint: {auditLogsEndpoint}
                  {{- end }}
                    auth:
                      authenticator: basicauth/logs
                  otlphttp/traces:
                  {{- if $istio }}
                    traces_endpoint: http://{regionalClusterName}-vmauth:8427/vti/insert/opentelemetry/v1/traces
                  {{- else if $m2r }}
                    traces_endpoint: https://vmauth.{regionalDomain}/vti/insert/opentelemetry/v1/traces
                  {{- else }}
                    traces_endpoint: {tracesEndpoint}
                  {{- end }}
                    auth:
                      authenticator: basicauth/traces
                {{- end }}

                  prometheusremotewrite:
                  {{- if not $m2m }}
                    {{- if $istio }}
                    endpoint: http://{regionalClusterName}-vmauth:8427/vm/insert/0/prometheus/api/v1/write
                    {{- else if $m2r }}
                    endpoint: https://vmauth.{regionalDomain}/vm/insert/0/prometheus/api/v1/write
                    {{- else }}
                    endpoint: {writeMetricsEndpoint}
                    {{- end }}
                    auth:
                      authenticator: basicauth/metrics
                  {{- end }}

                    external_labels:
                      cluster: {childClusterName}
                      clusterNamespace: {childClusterNamespace}

          {{- if not $m2m }}
          opencost:
            opencost:
              prometheus:
                existingSecretName: {vmuserSecretName}
                external:
                {{- if $istio }}
                  url: http://{regionalClusterName}-vmauth:8427/vm/select/0/prometheus
                {{- else if $m2r }}
                  url: https://vmauth.{regionalDomain}/vm/select/0/prometheus
                {{- else }}
                  url: {readMetricsEndpoint}
                {{- end }}
              exporter:
                defaultClusterId: {childClusterName}
                extraEnv:
                  CLUSTER_NAME: {childClusterName}
                  EMIT_KSM_V1_METRICS: "false"
                  EMIT_KSM_V1_METRICS_ONLY: "true"
          {{- end }}

          ` | replace "{childClusterName}" $childClusterName | replace "{childClusterNamespace}" $childClusterNamespace | replace "{vmuserSecretName}" $vmuserSecretName | replace "{vmuserSecretVersion}" $vmuserSecretVersion
          {{- if $istio }} | replace "{regionalClusterName}" $regionalClusterName
          {{- else if $m2r }} | replace "{regionalDomain}" $regionalDomain
          {{- else if not $mgmt }} | replace "{tracesEndpoint}" $tracesEndpoint | replace "{logsEndpoint}" $logsEndpoint | replace "{auditLogsEndpoint}" $auditLogsEndpoint | replace "{writeMetricsEndpoint}" $writeMetricsEndpoint | replace "{readMetricsEndpoint}" $readMetricsEndpoint
          {{- end }} | fromYaml {{`}}`}}

          {{`{{`}} $globalValuesFromHelm := `{{ $globalGlobal | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $mergedValues := mergeOverwrite (dict) $globalValuesFromHelm $collectorsValuesHere $collectorsValuesFromHelm $mgmtCollectorsValuesFromHelm $collectorsValuesFromAnnotation {{`}}`}}

        {{- if not $m2m }}
          {{`{{`}} $defaultCRConfigEnv := `
          env:
            - name: KOF_VM_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {vmuserSecretName}
            - name: KOF_VM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {vmuserSecretName}
          ` | replace "{vmuserSecretName}" $vmuserSecretName | fromYaml {{`}}`}}
          {{`{{`}} $env := concat (get $defaultCRConfigEnv "env") (dig "opentelemetry-kube-stack" "defaultCRConfig" "env" (list) $mergedValues) {{`}}`}}
          {{`{{`}} $mergedValues = mergeOverwrite $mergedValues (dict "opentelemetry-kube-stack" (dict "defaultCRConfig" (dict "env" $env))) {{`}}`}}
        {{- end }}

          {{`{{`}} $mergedValues | toYaml | nindent 4 {{`}}`}}

    templateResourceRefs:
    {{- if $m2r }}
    - identifier: RegionalKCMCluster
      optional: true
      resource:
        apiVersion: cluster.x-k8s.io/v1beta1
        kind: Cluster
        name: "{{ $.Values.fromManagement.toRegionalCluster.name }}"
        namespace: "{{ $.Values.fromManagement.toRegionalCluster.namespace }}"
    - identifier: RegionalSveltosCluster
      optional: true
      resource:
        apiVersion: lib.projectsveltos.io/v1beta1
        kind: SveltosCluster
        name: "{{ $.Values.fromManagement.toRegionalCluster.name }}"
        namespace: "{{ $.Values.fromManagement.toRegionalCluster.namespace }}"
    {{- else if not $mgmt }}
    - identifier: ChildConfig
      resource:
        apiVersion: v1
        kind: ConfigMap
        name: kof-cluster-config-{{`{{`}} .Cluster.metadata.name {{`}}`}}
        namespace: "{{`{{`}} .Cluster.metadata.namespace {{`}}`}}"
    - identifier: ChildKCMCluster
      optional: true
      resource:
        apiVersion: cluster.x-k8s.io/v1beta1
        kind: Cluster
        name: "{{`{{`}} .Cluster.metadata.name {{`}}`}}"
        namespace: "{{`{{`}} .Cluster.metadata.namespace {{`}}`}}"
    - identifier: ChildSveltosCluster
      optional: true
      resource:
        apiVersion: lib.projectsveltos.io/v1beta1
        kind: SveltosCluster
        name: "{{`{{`}} .Cluster.metadata.name {{`}}`}}"
        namespace: "{{`{{`}} .Cluster.metadata.namespace {{`}}`}}"
    {{- end }}

    {{- if not $m2m }}
    - identifier: StorageVMUserCredentials
      optional: true
      resource:
        apiVersion: v1
        kind: Secret
        {{- if $m2r }}
        name: kof-vmuser-creds-admin-{{`{{`}} printf "kof-%s/%s" "{{ $.Values.fromManagement.toRegionalCluster.name }}" "{{ $.Values.fromManagement.toRegionalCluster.namespace }}" | adler32sum {{`}}`}}
        {{- else }}
        name: kof-vmuser-creds-{{`{{`}} printf "kof-cluster-config-%s/%s" .Cluster.metadata.name .Cluster.metadata.namespace | adler32sum {{`}}`}}
        {{- end }}
        namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- end }}
