apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: kof-child-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
  serviceSpec:
    priority: 100
    services:

      - name: cert-manager
        namespace: kof
        template: cert-manager-1-16-2
        values: |
          cert-manager:
            crds:
              enabled: true

      - name: kof-operators
        namespace: kof
        template: kof-operators-{{ .Values.kcm.kof.charts.operators.version | replace "." "-" }}

      - name: kof-collectors
        namespace: kof
        template: kof-collectors-{{ .Values.kcm.kof.charts.collectors.version | replace "." "-" }}
        values: |
          {{/*
            We read the label of the **child** cluster for now.

            Upcoming `kof-operator` should read it from the **regional** cluster instead,
            and create this `MultiClusterService` dynamically.
          */}}
          global:
            clusterName: {{`{{ .Cluster.metadata.name }}`}}
          opencost:
            enabled: true
            opencost:
              prometheus:
                username_key: username
                password_key: password
                existingSecretName: storage-vmuser-credentials
                external:
                  url: https://vmauth.{{`{{ index .Cluster.metadata.labels "k0rdent.mirantis.com/kof-regional-domain" }}`}}/vm/select/0/prometheus
              exporter:
                defaultClusterId: {{`{{ .Cluster.metadata.name }}`}}
          kof:
            logs:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
              endpoint: https://vmauth.{{`{{ index .Cluster.metadata.labels "k0rdent.mirantis.com/kof-regional-domain" }}`}}/vls/insert/opentelemetry/v1/logs
            metrics:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
              endpoint: https://vmauth.{{`{{ index .Cluster.metadata.labels "k0rdent.mirantis.com/kof-regional-domain" }}`}}/vm/insert/0/prometheus/api/v1/write
            traces:
              endpoint: https://jaeger.{{`{{ index .Cluster.metadata.labels "k0rdent.mirantis.com/kof-regional-domain" }}`}}/collector
