apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: kof-child-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
      k0rdent.mirantis.com/istio-role: child

  templateResourceRefs:
    - identifier: ChildConfig
      resource:
        apiVersion: v1
        kind: ConfigMap
        name: kof-cluster-config-{{`{{ .Cluster.metadata.name }}`}}
        namespace: {{ .Values.kcm.namespace }}

  helmCharts:

    - repositoryName:   kof
      repositoryURL:    {{ .Values.kcm.kof.repo.url }}
      {{- if .Values.kcm.kof.repo.insecure }}
      registryCredentialsConfig:
        plainHTTP: true
      {{- end }}
      chartName:        kof-operators
      chartVersion:     {{ .Values.kcm.kof.charts.operators.version }}
      releaseName:      kof-operators
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install

    - repositoryName:   kof
      repositoryURL:    {{ .Values.kcm.kof.repo.url }}
      {{- if .Values.kcm.kof.repo.insecure }}
      registryCredentialsConfig:
        plainHTTP: true
      {{- end }}
      chartName:        kof-collectors
      chartVersion:     {{ .Values.kcm.kof.charts.collectors.version }}
      releaseName:      kof-collectors
      releaseNamespace: {{ .Release.Namespace }}
      helmChartAction:  Install
      values: |
        global:
          clusterName: {{`{{ .Cluster.metadata.name }}`}}
        kof:
          tmp: |
            {{`{{ $regionalClusterName := getField "ChildConfig" "data.regional_cluster_name" }}`}}
          logs:
            endpoint: http://{{`{{ $regionalClusterName }}`}}-logs/insert/opentelemetry/v1/logs
          metrics:
            endpoint: http://{{`{{ $regionalClusterName }}`}}-vminsert/insert/0/prometheus/api/v1/write
          traces:
            endpoint: http://{{`{{ $regionalClusterName }}`}}-jaeger-collector/collector
        opencost:
          enabled: true
          opencost:
            prometheus:
              external:
                url: http://{{`{{ $regionalClusterName }}`}}-vmselect/select/0/prometheus
            exporter:
              defaultClusterId: {{`{{ .Cluster.metadata.name }}`}}
