---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kof.k0rdent.mirantis.com
  resources:
  - promxyservergroups
  - vtstorageconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kof.k0rdent.mirantis.com
  resources:
  - promxyservergroups/finalizers
  - vtstorageconnections/finalizers
  verbs:
  - update
- apiGroups:
  - kof.k0rdent.mirantis.com
  resources:
  - promxyservergroups/status
  - vtstorageconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vtclusters
  verbs:
  - get
  - list
  - patch
  - update
  - watch
