{{- if index .Values "victoria-traces-cluster" "enabled" }}
apiVersion: kof.k0rdent.mirantis.com/v1beta1
kind: VTStorageConnection
metadata:
  name: {{ .Release.Name }}-vt-cluster
  namespace: {{ .Release.Namespace }}
spec:
  vt_cluster_ref:
    name: kof-mothership-multilevel-cluster
    namespace: {{ .Release.Namespace }}
  target_storage_node:
    address: "{{ .Release.Name }}-vt-cluster-vtselect.{{ .Release.Namespace }}.svc:10471"
    secret:
      name: storage-vmuser-credentials
      username_key: username
      password_key: password
    tls_config:
      enabled: false
      insecure_skip_verify: false
{{- end }}
    