kcm:
  namespace: kcm-system
  kof:
    # -- Repo of `kof-*` helm charts.
    repo:
      name: kof
      spec:
        type: oci
        url: oci://ghcr.io/k0rdent/kof/charts
kof:
  namespace: kof
k0rdent-istio:
  rootCA:
    enabled: true
  intermediateCAs:
    mothership:
      certificate: true
      issuer: true
  telemetry:
    traces_sampling_percentage: 100
  operator:
    enabled: true
    # TODO delete it after creating istio helm chart repo
    image:
      registry: docker.io/library
      repository: istio-operator-controller
  global:
    caAddress: cert-manager-istio-csr.istio-system.svc:443
    meshID: kof
    externalIstiod: true
    multiCluster:
      clusterName: mothership
    network: mothership-network
    meshConfig:
      accessLogFile: /dev/stdout
  istiod:
    meshConfig:
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: kof-collectors-daemon-collector.kof.svc.cluster.local
            resource_detectors:
              environment: {}
  cert-manager-istio-csr:
    app:
      certmanager:
        issuer:
          name: k0rdent-istio-mothership-ca
      server:
        clusterID: mothership
