{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmcluster.enabled }}
{{- $global := .Values.global | default dict }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- $spec := deepCopy .Values.victoriametrics.vmcluster.spec }}
  {{- if $global.storageClass }}
  {{- $_ := set $spec.vmselect.storage.volumeClaimTemplate.spec "storageClassName" $global.storageClass }}
  {{- $_ := set $spec.vmstorage.storage.volumeClaimTemplate.spec "storageClassName" $global.storageClass }}
  {{- end }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
{{- end }}
