
{{- $vtc := index .Values "victoria-traces-multilevel-select" -}}
{{- if and $vtc.enabled $vtc.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-vt-multilevel-select
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: {{ .Release.Name }}-multilevel-select
      app.kubernetes.io/name: vtselect
      managed-by: vm-operator
{{- end }}
