{{- $vtc := index .Values "victoria-traces-multilevel-cluster" -}}
{{- if $vtc.enabled }}
apiVersion: operator.victoriametrics.com/v1
kind: VTCluster
metadata:
  name: {{ .Release.Name }}-multilevel-cluster
  namespace: {{ .Release.Namespace }}
spec:
  select:
    replicaCount: {{ $vtc.replicaCount }}
    image:
      tag: {{ $vtc.image.tag }}
    extraArgs:
      {{- if $vtc.extraArgs }}
      {{- toYaml $vtc.extraArgs | nindent 6 }}
      {{- end }}
      {{- if $vtc.allowPartialResponse }}
      search.allowPartialResponse: "true"
      {{- end }}
  insert:
    replicaCount: 0
  storage:
    replicaCount: 0
{{- end }}