{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kof-coredns-patch
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kof-coredns-patch
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["coredns"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kof-coredns-patch
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kof-coredns-patch
subjects:
  - kind: ServiceAccount
    name: kof-coredns-patch
    namespace: kube-system
{{- end }}
