{{- if .Values.istio_endpoints }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name}}-cross-network-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "*.local"
{{- end }}
