{{- if .Values.jaeger.enabled }}
{{- if .Values.istio_endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.clusterName }}-jaeger-collector
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: grpc-jaeger
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: http-c-tchan-trft
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: http-c-binary-trft
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: admin-http
    port: 14269
    protocol: TCP
    targetPort: 14269
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: kof-storage-jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: kof-storage-jaeger
    app.kubernetes.io/part-of: jaeger
  type: ClusterIP
{{- end }}
{{- end }}
