{
 "title": "VictoriaLogs Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "datasource",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "k8s.cluster.name:~\"$cluster\""
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "k8s.cluster.name:~\"$cluster\" k8s.node.name:~\"$node\""
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "k8s.cluster.name:~\"$cluster\" k8s.node.name:~\"$node\" k8s.namespace.name:~\"$namespace\""
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "k8s.cluster.name:~\"$cluster\" k8s.node.name:~\"$node\" k8s.namespace.name:~\"$namespace\" k8s.pod.name:~\"$pod\""
    }
   },
   {
    "name": "severity",
    "label": "severity",
    "query": "Info : INFO,Debug : DEBUG,Warning : WARN,Error : ERROR,Fatal : FATAL"
   },
   { "name": "limit", "label": "limit", "query": "100, 500, 1000, 2000" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Logs with \"Fatal\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:=\"FATAL\" OR severity:=\"FATAL\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Logs with \"Error\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:=\"ERROR\" OR severity:=\"ERROR\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Logs with \"Warn\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:=\"WARN\" OR severity:=\"WARN\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Logs with \"Info\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:=\"INFO\" OR severity:=\"INFO\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Logs with \"Debug\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:=\"DEBUG\" OR severity:=\"DEBUG\"\n| stats count()"
    }
   ]
  },
  {
   "title": "Logs | Severity: $severity",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:~\"$severity\" OR severity:~\"$severity\"",
     "maxLines": 2000
    }
   ]
  },
  {
   "title": "Pods Logs Severity Count | Severity: $severity",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:~\"$severity\" OR severity:~\"$severity\"\n| stats by (severity_text, k8s.pod.name) count() hits\n| sort by (hits) desc"
    }
   ]
  },
  {
   "title": "Logs by Namespace | Severity: $severity",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "k8s.namespace.name:~\".*\"\nk8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nseverity_text:~\"$severity\" OR severity:~\"$severity\"\n| stats by (k8s.namespace.name) count() total\n| sort by(total) desc",
     "legendFormat": "{{`{{k8s.namespace.name}}`}}"
    }
   ]
  },
  {
   "title": "Logs Rate - $pod | Severity: $severity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:~\"$severity\" OR severity:~\"$severity\"\n| stats by (k8s.pod.name,k8s.container.name) rate() logs_rate\n| filter logs_rate: > 0",
     "legendFormat": "{{`{{k8s.pod.name}}`}}/{{`{{k8s.container.name}}`}}"
    }
   ]
  },
  {
   "title": "Top Field-Value Pairs | Severity: $severity",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:~\"$severity\" OR severity:~\"$severity\"\n| facets 3\n| sort by(hits) desc"
    }
   ]
  },
  {
   "title": "Top 10 Log Patterns | Severity: $severity",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 36 },
   "targets": [
    {
     "expr": "k8s.cluster.name:~\"$cluster\"\nk8s.node.name:~\"$node\"\nk8s.namespace.name:~\"$namespace\"\nk8s.pod.name:~\"$pod\"\nk8s.container.name:~\"$container\"\nseverity_text:~\"$severity\" OR severity:~\"$severity\"\n| collapse_nums prettify\n| top 10 by(_msg)"
    }
   ]
  }
 ]
}