{{- with index .Values "cert-manager"  }}
{{- if and ( index . "enabled" | default false) (index . "cluster-issuer" "create") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager.cluster-issuer.name" $ }}
spec:
{{- if eq (index . "cluster-issuer" "provider") "letsencrypt" }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
{{- else if eq (index . "cluster-issuer" "provider") "self-signed" }}
  selfSigned: {}
{{- end }}
{{- end }}
{{- end }}
