name: Generate Helm documentation
on:
  - pull_request
jobs:
  generate:
    runs-on: ubuntu-latest
    # Don't use `permissions: contents: write` as it applies to base repo only.
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts/kof-mothership
          template-files: charts/kof-mothership/README.md.gotmpl
          fail-on-diff: true
          # Don't use `git-push: true` because `pull_request` event is sent to the base repo only,
          # and its token cannot push to the forked repo branch.
          # A workaround with repo-scoped `Personal access tokens` of ALL contributors
          # stored as secrets in the base repo and mapped to `head.repo` is an overkill.
