name: Release Charts

on:
  push:
    tags:
      - "*"

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install YQ
        uses: mikefarah/yq@master

      - name: Get outputs
        id: vars
        run: |
          GIT_VERSION=$(git describe --tags --always)
          echo "version=${GIT_VERSION}" >> $GITHUB_OUTPUT

      - name: Setup charts
        run: |
          for dir in $(ls -d charts/*/); do
            yq -i '.version = "${{ steps.vars.outputs.version }}"' "$dir/Chart.yaml"
            yq -i '.appVersion = "${{ steps.vars.outputs.version }}"' "$dir/Chart.yaml"
            yq '.dependencies[] | select(.repository | test("^https?://")) | "helm repo add " + .name + " " + .repository' $dir/Chart.yaml | sh
            helm dependency update $dir;
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
