name: "Build and push kof helm charts to oci://ghcr.io/k0rdent/kof/charts"
# Usage: Create a new tag at https://github.com/k0rdent/kof/releases/new
# Test: Fork kof repo. Create a tag there. Check how charts are pushed to your OCI repo.

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        # Only a single commit is fetched by default, not whole tree.

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install YQ
        uses: mikefarah/yq@v4

      - name: Build charts with version = tag
        run: |
          mkdir build
          for dir in charts/*
          do
            yq '.dependencies[] | select(.repository | test("^https?://"))
              | "helm repo add " + .name + " " + .repository' "$dir/Chart.yaml" | sh
            helm dependency update "$dir"

            helm package "$dir" \
              --version "${{ github.ref_name }}" \
              --app-version "${{ github.ref_name }}"

            chart_name=$(yq .name "$dir/Chart.yaml")
            mv $chart_name-${{ github.ref_name }}.tgz build/
          done
          echo
          echo "Built:"
          ls build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: |
          repo=oci://ghcr.io/${{ github.repository }}/charts
          for chart in build/*
          do
            echo
            echo "Pushing $chart to $repo"
            helm push "$chart" "$repo"
          done
