name: Test Helm Charts
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release-*
    paths:
      - "promxy-operator/**"
      - "charts/**"
      - "!**.md"

env:
  GO_VERSION: "1.23"

jobs:
  build:
    concurrency:
      group: build-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    name: Build and Unit Test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      pr: ${{ steps.pr.outputs.result }}
    permissions:
      packages: write
    steps:
      - name: Get PR ref
        uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Unit tests
        working-directory: ./promxy-operator
        run: |
          make test

  setup-kind-cluster:
    name: Setup Kind Cluster & Local Registry
    runs-on: ubuntu-latest
    needs: build  # Changed to depend on build, removing unknown dependency
    steps:
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create Kind Cluster
        run: |
          kind create cluster --name kof-cluster
      - name: Install Local Registry
        run: |
          docker network create kind || true
          docker run -d --restart=always -p "5001:5001" --network=kind --name "kind-registry" registry:2
          echo "Registry installed"

  setup-kcm:
    name: Install and Apply KCM
    runs-on: ubuntu-latest
    needs: setup-kind-cluster
    steps:
      - name: Checkout KCM repository
        uses: actions/checkout@v4
        with:
          repository: k0rdent/kcm
          ref: main  # Change this if you need a different branch
      - name: Install KCM CLI
        run: |
          make cli-install
      - name: Apply KCM Dev Configuration
        run: |
          make dev-apply

  setup-kof:
    name: Install and Deploy KOF
    runs-on: ubuntu-latest
    needs: setup-kcm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install KOF CLI
        run: |
          make cli-install
      - name: Wait for Local Registry
        run: |
          echo "Checking if registry is running..."
          for i in {1..10}; do
            if curl -s http://127.0.0.1:5001/v2/; then
              echo "Registry is UP!"
              exit 0
            fi
            echo "Waiting for registry to start..."
            sleep 5
          done
          echo "Registry failed to start!"
          exit 1  # Fail the job if the registry is unreachable 
     - name: Push KOF Helm Charts
        run: |
          make helm-push
      - name: Deploy KOF Components
        run: |
          make dev-operators-deploy
          make dev-ms-deploy-cloud
          make dev-storage-deploy
          make dev-collectors-deploy

  kind-deploy:
    name: Deploy to Kind
    runs-on: ubuntu-latest
    needs: setup-kof
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Kind Deployment
        run: |
          make kind-deploy










