name: Test Helm Charts on KOF

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release-*
    paths:
      - "promxy-operator/**"
      - "charts/**"
      - "!**.md"

env:
  GO_VERSION: "1.23"

jobs:
  build:
    concurrency:
      group: build-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      pr: ${{ steps.pr.outputs.result }}
    permissions:
      packages: write
    steps:
      - name: Get PR ref
        uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

  setup-kind-cluster:
    name: Setup Kind Cluster
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create Kind Cluster
        run: |
          kind create cluster --name kof-cluster


  setup-kof-and-kcm:
    name: Install and Apply KCM, Then Deploy KOF
    runs-on: ubuntu-latest
    needs: setup-kind-cluster
    steps:
      # Step 1: Checkout the KCM repository
      - name: Checkout KCM repository
        uses: actions/checkout@v4
        with:
          repository: k0rdent/kcm
          ref: main  # Change if a different branch is needed
          path: kcm-repo  # Check out into a separate directory

      # Step 2: Install KCM CLI
      - name: Install KCM CLI
        run: |
          cd kcm-repo  # Run inside the correct repo
          make cli-install

      # Step 3: Apply KCM Dev Configuration
      - name: Apply KCM Dev Configuration
        run: |
          cd kcm-repo  # Run inside the correct repo
          make dev-apply

      # Step 4: Checkout the main repository for KOF
      - name: Checkout repository for KOF
        uses: actions/checkout@v4

      # Step 5: Install KOF CLI
      - name: Install KOF CLI
        run: |
          make cli-install

      # Step 6: Push KOF Helm Charts
      - name: Push KOF Helm Charts
        run: |
          make helm-push

      # Step 7: Deploy KOF Components
      - name: Deploy KOF Components
        run: |
          make dev-operators-deploy
          make dev-ms-deploy-cloud
          make dev-storage-deploy
          make dev-collectors-deploy


