name: Test Helm Charts
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release-*
    paths:
      - "promxy-operator/**"
      - "charts/**"
      - "!**.md"

env:
  GO_VERSION: "1.23"

jobs:
  build:
    concurrency:
      group: build-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    name: Build and Unit Test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      pr: ${{ steps.pr.outputs.result }}
    permissions:
      packages: write
    steps:
      - name: Get PR ref
        uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

    setup-kof:
    name: Install and Deploy KOF
    runs-on: ubuntu-latest
    needs: setup-kcm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install KOF CLI
        run: |
          make cli-install
      - name: Push KOF Helm Charts
        run: |
          make helm-push
      - name: Deploy KOF Components
        run: |
          make dev-operators-deploy
          make dev-ms-deploy-cloud
          make dev-storage-deploy
          make dev-collectors-deploy
